# Design Checker API Specification
apiVersion: v1
kind: APISpec

metadata:
  id: designchecker
  name: Design Checker
  version: 1.0.0
  port: 5019
  host: design-checker-api
  description: P&ID 도면 설계 오류 검출 및 규정 검증 API
  author: AX Team
  tags:
    - analysis
    - pid
    - validation

server:
  endpoint: /api/v1/check
  method: POST
  contentType: multipart/form-data
  timeout: 60
  healthEndpoint: /api/v1/health

blueprintflow:
  category: analysis
  color: "#ef4444"
  icon: ShieldCheck
  requiresImage: false

inputs:
  - name: symbols
    type: array
    required: true
    description: YOLO 검출 결과 (model_type=pid_class_aware 사용)
  - name: connections
    type: array
    required: true
    description: PID Analyzer 연결 분석 결과
  - name: lines
    type: array
    required: false
    description: Line Detector 결과
  - name: texts
    type: array
    required: false
    description: OCR 텍스트 결과 (BWMS 규칙 검사에 필요)

outputs:
  - name: violations
    type: array
    description: 위반 사항 목록
  - name: summary
    type: object
    description: 검사 요약
  - name: compliance_score
    type: number
    description: 규정 준수율 (0-100%)

parameters:
  - name: categories
    type: select
    options:
      - all
      - connectivity
      - symbol
      - labeling
      - specification
      - standard
      - safety
      - bwms
    default: all
    description: 검사할 규칙 카테고리 (all=전체)
  - name: severity_threshold
    type: select
    options:
      - error
      - warning
      - info
    default: info
    description: 보고할 최소 심각도
  - name: include_bwms
    type: boolean
    default: true
    description: BWMS 규칙 포함 여부 (TECHCROSS 전용 7개 규칙)

i18n:
  ko:
    label: Design Checker
    description: P&ID 도면 설계 오류 검출 및 규정 검증
  en:
    label: Design Checker
    description: P&ID design error detection and rule validation

resources:
  gpu:
    vram: "N/A"
    minVram: 0
    recommended: "CPU 전용"
    cudaVersion: "N/A"
  cpu:
    ram: "~1GB"
    minRam: 512
    cores: 2
    note: "규칙 기반 검증 - 매우 가벼움"

# OpenAPI Examples (2025-12-31 추가)
openapi:
  requestExamples:
    - name: "전체 규칙 검사"
      description: "모든 카테고리 규칙 검사"
      json:
        symbols:
          - class_name: "valve"
            tag: "V-001"
            bbox: {x1: 100, y1: 200, x2: 150, y2: 250}
          - class_name: "pump"
            tag: "P-001"
            bbox: {x1: 300, y1: 400, x2: 380, y2: 480}
        connections:
          - from: "V-001"
            to: "P-001"
            type: "process"
        categories: "all"
        severity_threshold: "warning"
        include_bwms: true

    - name: "BWMS 전용"
      description: "TECHCROSS BWMS 규칙만 검사"
      json:
        symbols: []
        connections: []
        texts:
          - text: "ECS-100"
            bbox: [100, 50, 200, 80]
        categories: "bwms"
        include_bwms: true

  responseExamples:
    - name: "성공 응답"
      statusCode: 200
      response:
        status: "success"
        data:
          violations:
            - rule_id: "CONN-001"
              category: "connectivity"
              severity: "error"
              message: "밸브 V-003이 어떤 배관에도 연결되지 않음"
              location: {x: 500, y: 300}
            - rule_id: "BWMS-002"
              category: "bwms"
              severity: "warning"
              message: "ECS 시스템에 필수 압력 센서 누락"
          summary:
            total_rules: 27
            checked: 27
            passed: 25
            failed: 2
          compliance_score: 92.6
        processing_time: 0.35
