# DocTR API Specification
apiVersion: v1
kind: APISpec

metadata:
  id: doctr
  name: DocTR
  version: 1.0.0
  host: doctr-api
  port: 5014
  description: "DocTR - 2단계 파이프라인 (Detection + Recognition), Apache 2.0"
  author: AX Team
  tags:
    - ocr
    - document
    - detection

server:
  endpoint: /api/v1/ocr
  method: POST
  contentType: multipart/form-data
  timeout: 60
  healthEndpoint: /api/v1/health

blueprintflow:
  category: ocr
  color: "#10b981"
  icon: FileSearch
  requiresImage: true

inputs:
  - name: image
    type: Image
    required: true
    description: 입력 이미지 (PNG, JPEG, PDF)

outputs:
  - name: texts
    type: TextResult[]
    description: 인식된 텍스트 배열
  - name: full_text
    type: string
    description: 전체 텍스트
  - name: pages
    type: object[]
    description: 페이지별 상세 결과

parameters:
  - name: det_arch
    type: string
    default: "db_resnet50"
    description: Detection 모델
    uiType: select
    options:
      - db_resnet50
      - db_mobilenet_v3_large
      - linknet_resnet18
  - name: reco_arch
    type: string
    default: "crnn_vgg16_bn"
    description: Recognition 모델
    uiType: select
    options:
      - crnn_vgg16_bn
      - crnn_mobilenet_v3_small
      - master
  - name: straighten_pages
    type: boolean
    default: false
    description: 페이지 정렬
    uiType: checkbox
  - name: export_as_xml
    type: boolean
    default: false
    description: XML로 내보내기
    uiType: checkbox
  - name: visualize
    type: boolean
    default: true
    description: 오버레이 이미지 생성
    uiType: checkbox

mappings:
  input:
    file: image
  output:
    texts: data.texts
    full_text: data.full_text
    pages: data.pages

i18n:
  ko:
    label: DocTR
    description: "2단계 파이프라인 OCR (Detection + Recognition)"
  en:
    label: DocTR
    description: "2-stage pipeline OCR (Detection + Recognition)"

resources:
  gpu:
    vram: "~2GB"
    minVram: 1500
    recommended: "GTX 1060 이상"
    cudaVersion: "11.8+"
  cpu:
    ram: "~4GB"
    minRam: 2048
    cores: 4
    note: "GPU 대비 4배 느림"
  parameterImpact:
    - parameter: det_arch
      impact: "모델 선택에 따라 메모리 차이"
      examples: "mobilenet:1.5GB, resnet50:2.5GB"

# OpenAPI Examples (2025-12-31 추가)
openapi:
  requestExamples:
    - name: "기본 OCR"
      description: "2단계 파이프라인 OCR"
      formData:
        file: "document.png"
        det_arch: "db_resnet50"
        reco_arch: "crnn_vgg16_bn"
        visualize: true

    - name: "경량 모델"
      description: "모바일/빠른 처리용"
      formData:
        file: "document.png"
        det_arch: "db_mobilenet_v3_large"
        reco_arch: "crnn_mobilenet_v3_small"
        straighten_pages: true

  responseExamples:
    - name: "성공 응답"
      statusCode: 200
      response:
        status: "success"
        data:
          texts:
            - text: "SPECIFICATION"
              confidence: 0.96
              bbox: [[50, 100], [200, 100], [200, 130], [50, 130]]
          full_text: "SPECIFICATION\nDRAWING NO: DWG-001\n..."
          pages:
            - page_idx: 0
              dimensions: [1200, 800]
              blocks: 15
        processing_time: 1.85
