# EDGNet Segmentation API Specification
apiVersion: v1
kind: APISpec

metadata:
  id: edgnet
  name: EDGNet Segmentation
  version: 1.0.0
  port: 5012
  description: 도면 구조 분석 및 레이어 분류
  author: AX Team
  tags:
    - segmentation
    - structure
    - layer

server:
  endpoint: /api/v1/segment
  method: POST
  contentType: multipart/form-data
  timeout: 90
  healthEndpoint: /api/v1/health

blueprintflow:
  category: segmentation
  color: "#8b5cf6"
  icon: Network
  requiresImage: true

inputs:
  - name: image
    type: Image
    required: true
    description: 분석할 도면 이미지

outputs:
  - name: components
    type: Component[]
    description: 분류된 컴포넌트 목록
  - name: total_components
    type: number
    description: 총 컴포넌트 수
  - name: visualized_image
    type: Image
    description: 세그멘테이션 시각화

parameters:
  - name: model
    type: select
    default: unet
    options:
      - unet
      - graphsage
    description: 세그멘테이션 모델

  - name: num_classes
    type: number
    default: 8
    min: 2
    max: 20
    description: 분류 클래스 수

  - name: visualize
    type: boolean
    default: true
    description: 시각화 생성

  - name: save_graph
    type: boolean
    default: false
    description: 그래프 구조 저장

  - name: vectorize
    type: boolean
    default: false
    description: 벡터화 출력

i18n:
  ko:
    label: EDGNet 세그멘테이션
    description: 도면의 구조를 분석하고 레이어별로 분류합니다
  en:
    label: EDGNet Segmentation
    description: Analyzes drawing structure and classifies by layers

# 프로파일 기반 기본값 (MODEL_DEFAULTS 패턴)
# 백엔드 models/edgnet-api/config/defaults.py와 동기화
profiles:
  default: drawing_classification
  available:
    - name: drawing_classification
      label: "도면 컴포넌트 분류"
      description: "Contour/Text/Dimension 3클래스 분류 (기본)"
      params:
        model: graphsage
        visualize: true
        num_classes: 3
        save_graph: false
        vectorize: false

    - name: text_detection
      label: "텍스트 영역 검출"
      description: "Text/Non-text 2클래스 분류"
      params:
        model: graphsage
        visualize: true
        num_classes: 2
        save_graph: false
        vectorize: false

    - name: edge_detection
      label: "엣지 검출"
      description: "UNet 기반 정밀 엣지 검출"
      params:
        model: unet
        visualize: true
        num_classes: 3
        save_graph: false
        vectorize: false

    - name: mask_extraction
      label: "마스크 추출"
      description: "세그멘테이션 마스크 추출 (후처리용)"
      params:
        model: unet
        visualize: false
        num_classes: 3
        save_graph: false
        vectorize: false

    - name: graph_analysis
      label: "그래프 구조 분석"
      description: "그래프 구조 JSON 저장 (연구용)"
      params:
        model: graphsage
        visualize: true
        num_classes: 3
        save_graph: true
        vectorize: false

    - name: fast
      label: "빠른 처리"
      description: "시각화 없이 빠른 분류만"
      params:
        model: graphsage
        visualize: false
        num_classes: 3
        save_graph: false
        vectorize: false

resources:
  gpu:
    vram: "~3GB"
    minVram: 2500
    recommended: "RTX 3060 이상"
    cudaVersion: "11.8+"
  cpu:
    ram: "~6GB"
    minRam: 4096
    cores: 4
    note: "GPU 대비 5배 느림"
  parameterImpact:
    - parameter: model
      impact: "graphsage 모델 시 VRAM 2배"
      examples: "unet:3GB, graphsage:6GB"
    - parameter: num_classes
      impact: "클래스 수↑ → 메모리↑"
      examples: "8클래스:3GB, 20클래스:5GB"

# OpenAPI Examples (2025-12-31 추가)
openapi:
  requestExamples:
    - name: "기본 세그멘테이션"
      description: "도면 구조 분석"
      formData:
        file: "drawing.png"
        model: "unet"
        num_classes: 8
        visualize: true

    - name: "그래프 기반 분석"
      description: "GraphSAGE 모델 사용"
      formData:
        file: "complex_drawing.png"
        model: "graphsage"
        num_classes: 12
        save_graph: true
        vectorize: true

  responseExamples:
    - name: "성공 응답"
      statusCode: 200
      response:
        status: "success"
        data:
          components:
            - class: "dimension"
              count: 25
              confidence: 0.92
            - class: "symbol"
              count: 15
              confidence: 0.88
            - class: "text"
              count: 42
              confidence: 0.95
          total_components: 82
          visualized_image: "data:image/png;base64,..."
        processing_time: 3.15
