# ESRGAN API Specification
apiVersion: v1
kind: APISpec

metadata:
  id: esrgan
  name: ESRGAN Upscaler
  version: 1.0.0
  port: 5010
  description: Real-ESRGAN 기반 이미지 업스케일링
  author: AX Team
  tags:
    - preprocessing
    - upscaling
    - enhancement
    - esrgan

server:
  endpoint: /api/v1/upscale
  method: POST
  contentType: multipart/form-data
  timeout: 120
  healthEndpoint: /health

blueprintflow:
  category: preprocessing
  color: "#f59e0b"
  icon: ZoomIn
  requiresImage: true

inputs:
  - name: image
    type: Image
    required: true
    description: 저해상도 입력 이미지

outputs:
  - name: image
    type: Image
    description: 업스케일된 이미지

parameters:
  - name: scale
    type: select
    default: "4"
    options:
      - "2"
      - "4"
    description: 업스케일 배율

  - name: denoise_strength
    type: number
    default: 0.5
    min: 0
    max: 1
    step: 0.1
    description: 노이즈 제거 강도

i18n:
  ko:
    label: ESRGAN 업스케일러
    description: 저품질 스캔 도면을 4배 업스케일하여 OCR 정확도 향상
  en:
    label: ESRGAN Upscaler
    description: 4x upscale low-quality scanned drawings to improve OCR accuracy

examples:
  - 저해상도 스캔 도면 업스케일
  - OCR 전처리로 정확도 향상

usageTips:
  - OCR 전에 사용하면 정확도가 크게 향상됩니다
  - 이미 고해상도인 경우 불필요합니다
  - GPU 사용시 훨씬 빠릅니다

resources:
  gpu:
    vram: "~4GB"
    minVram: 3000
    recommended: "RTX 3060 이상"
    cudaVersion: "11.8+"
  cpu:
    ram: "~8GB"
    minRam: 6144
    cores: 8
    note: "GPU 대비 20배 느림 (권장하지 않음)"
  parameterImpact:
    - parameter: scale
      impact: "4x 스케일 시 VRAM/RAM 급증"
      examples: "2x:2GB, 4x:4GB"

# OpenAPI Examples (2025-12-31 추가)
openapi:
  requestExamples:
    - name: "4x 업스케일"
      description: "저해상도 도면 4배 확대"
      formData:
        file: "low_res_drawing.png"
        scale: "4"
        denoise_strength: 0.5

    - name: "2x 업스케일 (노이즈 제거)"
      description: "스캔 노이즈 제거 + 2배 확대"
      formData:
        file: "scanned_drawing.png"
        scale: "2"
        denoise_strength: 0.8

  responseExamples:
    - name: "성공 응답"
      statusCode: 200
      response:
        status: "success"
        data:
          image: "data:image/png;base64,..."
          original_size: [640, 480]
          upscaled_size: [2560, 1920]
          scale_factor: 4
        processing_time: 3.25
