# Excel Export API Specification
apiVersion: v1
kind: APISpec

metadata:
  id: excelexport
  name: Excel Export
  version: 1.0.0
  port: 5020
  host: blueprint-ai-bom-backend
  description: P&ID 분석 결과를 Excel 파일로 내보냅니다. Equipment, Valve, Checklist, Deviation을 각 시트에 분리하여 정리합니다.
  author: AX Team
  tags:
    - export
    - excel
    - spreadsheet
    - analysis

server:
  endpoint: /api/v1/pid-features/{session_id}/export
  method: POST
  contentType: application/json
  timeout: 60
  healthEndpoint: /health

blueprintflow:
  category: analysis
  color: "#16a34a"
  icon: FileSpreadsheet
  requiresImage: false

inputs:
  - name: session_data
    type: SessionData
    required: true
    description: 워크플로우 분석 결과
  - name: image
    type: Image
    required: false
    description: 원본 이미지

outputs:
  - name: excel_url
    type: string
    description: Excel 다운로드 URL
  - name: filename
    type: string
    description: 파일명
  - name: summary
    type: ExportSummary
    description: 내보내기 요약

parameters:
  - name: export_type
    type: select
    options:
      - all
      - valve
      - equipment
      - checklist
      - deviation
    default: all
    description: 내보내기 범위 선택
  - name: project_name
    type: string
    default: ""
    description: 프로젝트명
  - name: drawing_no
    type: string
    default: ""
    description: 도면 번호
  - name: include_rejected
    type: boolean
    default: false
    description: 거부된 항목 포함 여부

i18n:
  ko:
    label: Excel Export
    description: P&ID 분석 결과를 Excel 파일로 내보냅니다
  en:
    label: Excel Export
    description: Export P&ID analysis results to Excel file

resources:
  cpu:
    ram: "~150MB"
    minRam: 100
    cores: 1
    note: openpyxl CPU 전용
