# GT Comparison API Specification
apiVersion: v1
kind: APISpec

metadata:
  id: gtcomparison
  name: GT Comparison
  version: 1.0.0
  port: 5020
  host: blueprint-ai-bom-backend
  description: Ground Truth와 YOLO 검출 결과를 비교하여 Precision, Recall, F1 스코어를 계산합니다.
  author: AX Team
  tags:
    - ground-truth
    - evaluation
    - metrics
    - precision
    - recall

server:
  endpoint: /api/ground-truth/compare
  method: POST
  contentType: application/json
  timeout: 30
  healthEndpoint: /health

blueprintflow:
  category: analysis
  color: "#f97316"
  icon: BarChart3
  requiresImage: false

inputs:
  - name: detections
    type: Detection[]
    required: true
    description: YOLO 검출 결과
  - name: image
    type: Image
    required: false
    description: 원본 이미지 (파일명 참조용)

outputs:
  - name: metrics
    type: GTMetrics
    description: 평가 지표 (Precision, Recall, F1)
  - name: tp_matches
    type: TPMatch[]
    description: True Positive 매칭 목록
  - name: fp_detections
    type: Detection[]
    description: False Positive 목록
  - name: fn_labels
    type: GTLabel[]
    description: False Negative GT 목록

parameters:
  - name: gt_file
    type: file
    default: ""
    description: GT 파일 경로
  - name: iou_threshold
    type: number
    default: 0.5
    min: 0.1
    max: 0.9
    step: 0.05
    description: IoU 임계값
  - name: class_agnostic
    type: boolean
    default: false
    description: 클래스 무시 모드
  - name: model_type
    type: select
    options:
      - bom_detector
      - engineering
      - pid_class_aware
      - pid_symbol
      - custom
    default: bom_detector
    description: 모델 타입

i18n:
  ko:
    label: GT Comparison
    description: Ground Truth와 검출 결과를 비교하여 메트릭 계산
  en:
    label: GT Comparison
    description: Compare detections with ground truth to calculate metrics

resources:
  cpu:
    ram: "~100MB"
    minRam: 64
    cores: 1
    note: CPU만 사용 (GPU 불필요)
