# PDF Export API Specification
apiVersion: v1
kind: APISpec

metadata:
  id: pdfexport
  name: PDF Export
  version: 1.0.0
  port: 5020
  host: blueprint-ai-bom-backend
  description: P&ID 분석 결과를 전문적인 PDF 리포트로 내보냅니다. TECHCROSS BWMS 스타일 표지 및 상세 목록을 포함합니다.
  author: AX Team
  tags:
    - export
    - pdf
    - report
    - analysis
    - techcross

server:
  endpoint: /api/v1/pid-features/{session_id}/export/pdf
  method: POST
  contentType: application/json
  timeout: 60
  healthEndpoint: /health

blueprintflow:
  category: analysis
  color: "#dc2626"
  icon: FileText
  requiresImage: false

inputs:
  - name: session_data
    type: SessionData
    required: true
    description: 워크플로우 분석 결과
  - name: image
    type: Image
    required: false
    description: 원본 이미지

outputs:
  - name: pdf_url
    type: string
    description: PDF 다운로드 URL
  - name: filename
    type: string
    description: PDF 파일명
  - name: summary
    type: ExportSummary
    description: 내보내기 요약

parameters:
  - name: export_type
    type: select
    options:
      - all
      - valve
      - equipment
      - checklist
      - deviation
    default: all
    description: 내보내기 범위 선택
  - name: project_name
    type: string
    default: ""
    description: PDF 표지 프로젝트명
  - name: drawing_no
    type: string
    default: ""
    description: 도면 번호
  - name: include_rejected
    type: boolean
    default: false
    description: 거부된 항목 포함

i18n:
  ko:
    label: PDF Export
    description: P&ID 분석 결과를 PDF 리포트로 내보냅니다
  en:
    label: PDF Export
    description: Export P&ID analysis results to PDF report

resources:
  cpu:
    ram: "~200MB"
    minRam: 128
    cores: 1
    note: ReportLab PDF 생성 (CPU 전용)
