# PID Features API Specification
apiVersion: v1
kind: APISpec

metadata:
  id: pidfeatures
  name: PID Features
  version: 1.0.0
  port: 5020
  host: blueprint-ai-bom-backend
  description: TECHCROSS P&ID 통합 분석 노드. Valve Signal List, Equipment List, Design Checklist를 한 번에 검출합니다.
  author: AX Team
  tags:
    - pid
    - techcross
    - valve
    - equipment
    - checklist
    - bwms

server:
  endpoint: /api/v1/pid-features/{session_id}/valve-signal/detect
  method: POST
  contentType: application/json
  timeout: 120
  healthEndpoint: /health

blueprintflow:
  category: analysis
  color: "#8b5cf6"
  icon: Workflow
  requiresImage: true

inputs:
  - name: image
    type: Image
    required: true
    description: P&ID 도면 이미지
  - name: detections
    type: Detection[]
    required: false
    description: YOLO 검출 결과
  - name: ocr_results
    type: OCRResult[]
    required: false
    description: OCR 결과
  - name: lines
    type: Line[]
    required: false
    description: 라인 검출 결과

outputs:
  - name: valves
    type: Valve[]
    description: 밸브 목록
  - name: equipment
    type: Equipment[]
    description: 장비 목록
  - name: checklist
    type: ChecklistItem[]
    description: 체크리스트 결과
  - name: verification_queue
    type: VerificationItem[]
    description: 검증 대기 큐
  - name: session_id
    type: string
    description: 세션 ID

parameters:
  - name: features
    type: checkboxGroup
    options:
      - valve_signal
      - equipment
      - checklist
    default: ["valve_signal", "equipment", "checklist"]
    description: 활성화할 기능
  - name: product_type
    type: select
    options:
      - ALL
      - ECS
      - HYCHLOR
    default: ALL
    description: 제품 타입
  - name: confidence_threshold
    type: number
    default: 0.7
    min: 0.1
    max: 0.99
    step: 0.05
    description: 신뢰도 임계값
  - name: auto_verify_high_confidence
    type: boolean
    default: true
    description: 고신뢰도 자동 검증

i18n:
  ko:
    label: PID Features
    description: TECHCROSS P&ID 통합 분석 (Valve/Equipment/Checklist)
  en:
    label: PID Features
    description: TECHCROSS P&ID integrated analysis (Valve/Equipment/Checklist)

resources:
  cpu:
    ram: "~300MB"
    minRam: 200
    cores: 2
    note: 다중 API 호출
