# Tesseract OCR API Specification
apiVersion: v1
kind: APISpec

metadata:
  id: tesseract
  name: Tesseract OCR
  version: 1.0.0
  port: 5008
  description: Google Tesseract 기반 OCR 엔진
  author: AX Team
  tags:
    - ocr
    - tesseract
    - text-recognition

server:
  endpoint: /api/v1/ocr
  method: POST
  contentType: multipart/form-data
  timeout: 60
  healthEndpoint: /health

blueprintflow:
  category: ocr
  color: "#6366f1"
  icon: FileSearch
  requiresImage: true

inputs:
  - name: image
    type: Image
    required: true
    description: 분석할 이미지

outputs:
  - name: texts
    type: OCRResult[]
    description: 인식된 텍스트 목록
  - name: full_text
    type: string
    description: 전체 텍스트

parameters:
  - name: lang
    type: select
    default: eng
    options:
      - eng
      - kor
      - jpn
      - chi_sim
      - chi_tra
      - eng+kor
    description: 인식 언어

  - name: psm
    type: select
    default: "3"
    options:
      - "0"
      - "1"
      - "3"
      - "4"
      - "6"
      - "7"
      - "11"
      - "12"
      - "13"
    description: Page Segmentation Mode

  - name: output_type
    type: select
    default: data
    options:
      - string
      - data
      - dict
    description: 출력 형식

mappings:
  output:
    texts: texts
    full_text: full_text

i18n:
  ko:
    label: Tesseract OCR
    description: Google Tesseract 기반 범용 OCR
  en:
    label: Tesseract OCR
    description: Google Tesseract-based general OCR

examples:
  - 문서 텍스트 추출
  - 다국어 텍스트 인식

usageTips:
  - PSM 3은 자동 페이지 분할
  - PSM 6은 단일 블록으로 처리
  - OCR Ensemble과 함께 사용시 15% 가중치

resources:
  gpu:
    vram: "N/A"
    minVram: 0
    recommended: "CPU 전용"
    cudaVersion: "N/A"
  cpu:
    ram: "~1GB"
    minRam: 512
    cores: 2
    note: "CPU 전용 - 빠르고 가벼움"

# OpenAPI Examples (2025-12-31 추가)
openapi:
  requestExamples:
    - name: "기본 OCR"
      description: "영어 문서 텍스트 추출"
      formData:
        file: "document.png"
        lang: "eng"
        psm: "3"
        output_type: "data"

    - name: "한글+영어 혼합"
      description: "이중 언어 문서 인식"
      formData:
        file: "korean_doc.png"
        lang: "eng+kor"
        psm: "6"
        output_type: "data"

  responseExamples:
    - name: "성공 응답"
      statusCode: 200
      response:
        status: "success"
        data:
          texts:
            - text: "DRAWING TITLE"
              confidence: 0.92
              bbox: [50, 100, 200, 130]
            - text: "REV. A"
              confidence: 0.88
              bbox: [500, 100, 560, 130]
          full_text: "DRAWING TITLE\nREV. A\n..."
        processing_time: 0.45
