# Verification Queue API Specification
apiVersion: v1
kind: APISpec

metadata:
  id: verificationqueue
  name: Verification Queue
  version: 1.0.0
  port: 5020
  host: blueprint-ai-bom-backend
  description: Human-in-the-Loop 검증 큐를 관리합니다. 신뢰도가 낮은 항목을 검토하고 승인/거부/수정할 수 있습니다.
  author: AX Team
  tags:
    - verification
    - human-in-the-loop
    - queue
    - review

server:
  endpoint: /api/v1/pid-features/{session_id}/verify/queue
  method: GET
  contentType: application/json
  timeout: 30
  healthEndpoint: /health

blueprintflow:
  category: analysis
  color: "#f59e0b"
  icon: ClipboardCheck
  requiresImage: false

inputs:
  - name: session_id
    type: string
    required: true
    description: 세션 ID
  - name: verification_queue
    type: VerificationItem[]
    required: false
    description: 검증 대기 항목

outputs:
  - name: verified_items
    type: VerifiedItem[]
    description: 검증 완료 항목
  - name: rejected_items
    type: RejectedItem[]
    description: 거부된 항목
  - name: pending_items
    type: PendingItem[]
    description: 대기 중 항목
  - name: summary
    type: VerificationSummary
    description: 검증 현황 요약

parameters:
  - name: queue_filter
    type: select
    options:
      - all
      - valve
      - equipment
      - checklist
    default: all
    description: 큐 필터
  - name: sort_by
    type: select
    options:
      - confidence_asc
      - confidence_desc
      - type
      - created
    default: confidence_asc
    description: 정렬 기준
  - name: batch_size
    type: number
    default: 20
    min: 5
    max: 100
    description: 배치 크기
  - name: auto_approve_threshold
    type: number
    default: 0.95
    min: 0.8
    max: 1.0
    step: 0.01
    description: 자동 승인 임계값

i18n:
  ko:
    label: Verification Queue
    description: Human-in-the-Loop 검증 큐 관리
  en:
    label: Verification Queue
    description: Human-in-the-Loop verification queue management

resources:
  cpu:
    ram: "~100MB"
    minRam: 64
    cores: 1
    note: 세션 데이터 조회만
