# Vision-Language API Specification
apiVersion: v1
kind: APISpec

metadata:
  id: vl
  name: Vision-Language Model
  version: 1.0.0
  port: 5004
  description: 멀티모달 AI - 이미지 이해 및 질의응답
  author: AX Team
  tags:
    - ai
    - llm
    - vision
    - multimodal

server:
  endpoint: /api/v1/analyze
  method: POST
  contentType: application/json
  timeout: 120
  healthEndpoint: /api/v1/health

blueprintflow:
  category: ai
  color: "#ec4899"
  icon: Eye
  requiresImage: true
  recommendedInputs:
    - from: textinput
      field: text
      reason: 이미지에 대한 질문이나 프롬프트를 입력합니다

inputs:
  - name: image
    type: Image
    required: true
    description: 분석할 이미지
  - name: prompt
    type: string
    required: false
    description: 질문 또는 지시사항

outputs:
  - name: response
    type: string
    description: AI 응답
  - name: analysis
    type: object
    description: 상세 분석 결과

parameters:
  - name: model
    type: select
    default: qwen-vl
    options:
      - qwen-vl
      - llava
      - cogvlm
      - local
    description: Vision-Language 모델 선택

  - name: temperature
    type: number
    default: 0.7
    min: 0
    max: 2
    step: 0.1
    description: 응답 창의성 (높을수록 다양)

mappings:
  input:
    prompt: inputs.text
    image: inputs.image

i18n:
  ko:
    label: VL 모델
    description: 이미지를 이해하고 질문에 답변하는 멀티모달 AI
  en:
    label: VL Model
    description: Multimodal AI for image understanding and Q&A

resources:
  gpu:
    vram: "~8GB"
    minVram: 6000
    recommended: "RTX 4070 이상"
    cudaVersion: "11.8+"
  cpu:
    ram: "~16GB"
    minRam: 12288
    cores: 8
    note: "GPU 필수 권장"
  parameterImpact:
    - parameter: model
      impact: "모델에 따라 VRAM 차이"
      examples: "qwen-vl:8GB, llava:6GB, cogvlm:10GB"

# OpenAPI Examples (2025-12-31 추가)
openapi:
  requestExamples:
    - name: "도면 분류"
      description: "도면 유형 자동 분류"
      json:
        image: "base64_encoded_image..."
        prompt: "이 도면의 유형을 분류해주세요. (기계도면, P&ID, 전기도면, 건축도면 중)"
        model: "qwen-vl"
        temperature: 0.3

    - name: "부품 설명"
      description: "도면 내 부품 설명 요청"
      json:
        image: "base64_encoded_image..."
        prompt: "이 도면에서 주요 부품들을 설명해주세요."
        model: "qwen-vl"
        temperature: 0.7

  responseExamples:
    - name: "성공 응답"
      statusCode: 200
      response:
        status: "success"
        data:
          response: "이 도면은 P&ID(Piping and Instrumentation Diagram)입니다. 주요 구성요소로는 밸브, 펌프, 열교환기가 포함되어 있습니다."
          analysis:
            drawing_type: "P&ID"
            confidence: 0.92
            components_found: ["valve", "pump", "heat_exchanger"]
        processing_time: 2.15
