# YOLO P&ID Symbol Detector API Specification
apiVersion: v1
kind: APISpec

metadata:
  id: yolopid
  name: YOLO-PID
  version: 1.0.0
  port: 5017
  host: yolo-pid-api
  description: P&ID 심볼 검출 API (밸브, 펌프, 계기 등 50+ 클래스)
  author: AX Team
  tags:
    - detection
    - pid
    - yolo

server:
  endpoint: /api/v1/process
  method: POST
  contentType: multipart/form-data
  timeout: 60
  healthEndpoint: /health

blueprintflow:
  category: detection
  color: "#059669"
  icon: CircuitBoard
  requiresImage: true

inputs:
  - name: image
    type: Image
    required: true
    description: P&ID 도면 이미지

outputs:
  - name: detections
    type: array
    description: 검출된 P&ID 심볼 목록
  - name: statistics
    type: object
    description: 카테고리별 통계
  - name: visualization
    type: string
    description: 시각화 이미지 (base64)

parameters:
  - name: confidence
    type: number
    min: 0.1
    max: 1.0
    default: 0.25
    description: 신뢰도 임계값
  - name: iou
    type: number
    min: 0.1
    max: 1.0
    default: 0.45
    description: IoU 임계값
  - name: imgsz
    type: select
    options:
      - 320
      - 640
      - 1280
    default: 640
    description: 입력 이미지 크기
  - name: visualize
    type: boolean
    default: true
    description: 결과 시각화

i18n:
  ko:
    label: YOLO-PID
    description: P&ID 심볼 검출 (밸브, 펌프, 계기 등)
  en:
    label: YOLO-PID
    description: P&ID symbol detection (valves, pumps, instruments)
