# YOLO Detection API Specification
# BlueprintFlow 자동 통합을 위한 표준 스펙

apiVersion: v1
kind: APISpec

metadata:
  id: yolo
  name: YOLO Detection
  version: 1.0.0
  port: 5005
  description: YOLOv11 기반 기계 도면 심볼 검출 API
  author: AX Team
  tags:
    - detection
    - yolo
    - symbol
    - object-detection

server:
  endpoint: /api/v1/detect
  method: POST
  contentType: multipart/form-data
  timeout: 60
  healthEndpoint: /health

blueprintflow:
  category: detection
  color: "#10b981"
  icon: Target
  requiresImage: true
  recommendedInputs:
    - from: imageinput
      field: image
      reason: 도면 이미지를 입력으로 받아 심볼을 검출합니다

inputs:
  - name: image
    type: Image
    required: true
    description: 분석할 도면 이미지 (JPG, PNG)

outputs:
  - name: detections
    type: DetectionResult[]
    description: 검출된 심볼 목록 (위치, 종류, 신뢰도)
  - name: total_detections
    type: number
    description: 총 검출 개수
  - name: visualized_image
    type: Image
    description: 바운딩 박스가 그려진 시각화 이미지
  - name: processing_time
    type: number
    description: 처리 시간 (초)

parameters:
  - name: model_type
    type: select
    default: symbol-detector-v1
    options:
      - symbol-detector-v1
      - dimension-detector-v1
      - gdt-detector-v1
      - text-region-detector-v1
      - yolo11n-general
    description: 용도별 특화 모델 선택
    formField: model_type

  - name: confidence
    type: number
    default: 0.5
    min: 0
    max: 1
    step: 0.05
    description: 검출 신뢰도 임계값

  - name: iou
    type: number
    default: 0.45
    min: 0
    max: 1
    step: 0.05
    description: NMS IoU 임계값

  - name: imgsz
    type: number
    default: 1280
    min: 320
    max: 1920
    step: 32
    description: 입력 이미지 크기

  - name: visualize
    type: boolean
    default: true
    description: 결과 시각화 이미지 생성

  - name: task
    type: select
    default: detect
    options:
      - detect
      - segment
    description: 작업 유형 (detect/segment)

mappings:
  output:
    detections: data.detections
    total_detections: data.total_detections
    visualized_image: data.visualized_image
    processing_time: processing_time

i18n:
  ko:
    label: YOLO 검출
    description: 기계 도면에서 용접 기호, 베어링, 기어 등 14가지 심볼을 자동으로 검출합니다
    parameters:
      model_type: 모델 선택
      confidence: 신뢰도 임계값
      iou: NMS IoU 임계값
      imgsz: 이미지 크기
      visualize: 시각화 생성
      task: 작업 유형
  en:
    label: YOLO Detection
    description: Automatically detects 14 types of symbols including welding marks, bearings, and gears
    parameters:
      model_type: Model Selection
      confidence: Confidence Threshold
      iou: NMS IoU Threshold
      imgsz: Image Size
      visualize: Generate Visualization
      task: Task Type

examples:
  - 도면에서 용접 기호 위치 검출
  - 치수선 영역 자동 추출
  - GD&T 기호 식별

usageTips:
  - 복잡한 도면은 imgsz를 1920으로 올려보세요
  - 작은 심볼이 많으면 confidence를 0.3으로 낮춰보세요
  - 중복 검출이 많으면 iou를 0.6으로 올려보세요

# 리소스 요구사항
resources:
  gpu:
    vram: "~2GB"
    minVram: 1500
    recommended: "RTX 3060 이상"
    cudaVersion: "11.8+"
  cpu:
    ram: "~3GB"
    minRam: 2048
    cores: 4
    note: "GPU 대비 10배 느림"
  parameterImpact:
    - parameter: imgsz
      impact: "imgsz↑ → VRAM↑"
      examples: "640:1.5GB, 1280:2.5GB, 1920:4GB"
    - parameter: task
      impact: "segment 모드 시 VRAM 1.5배"
      examples: "detect:2GB, segment:3GB"
