import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: '1. System Overview',
      link: {type: 'doc', id: 'system-overview/index'},
      items: [
        'system-overview/architecture-map',
        'system-overview/service-catalog',
        'system-overview/tech-stack',
        'system-overview/port-network',
        'system-overview/architecture-decisions',
      ],
    },
    {
      type: 'category',
      label: '2. Analysis Pipeline',
      link: {type: 'doc', id: 'analysis-pipeline/index'},
      items: [
        'analysis-pipeline/vlm-classification',
        'analysis-pipeline/yolo-detection',
        'analysis-pipeline/ocr-processing',
        'analysis-pipeline/tolerance-analysis',
        'analysis-pipeline/revision-comparison',
      ],
    },
    {
      type: 'category',
      label: '3. BlueprintFlow',
      link: {type: 'doc', id: 'blueprintflow/index'},
      items: [
        'blueprintflow/node-catalog',
        'blueprintflow/dag-engine',
        'blueprintflow/templates',
        'blueprintflow/custom-api',
        'blueprintflow/optimization',
      ],
    },
    {
      type: 'category',
      label: '4. Agent Verification',
      link: {type: 'doc', id: 'agent-verification/index'},
      items: [
        'agent-verification/three-level-architecture',
        'agent-verification/api-reference',
        'agent-verification/dashboard',
      ],
    },
    {
      type: 'category',
      label: '5. BOM & Quoting',
      link: {type: 'doc', id: 'bom-generation/index'},
      items: [
        'bom-generation/detection-classes',
        'bom-generation/pricing-engine',
        'bom-generation/export-formats',
        'bom-generation/pdf-report',
      ],
    },
    {
      type: 'category',
      label: '6. P&ID Analysis',
      link: {type: 'doc', id: 'pid-analysis/index'},
      items: [
        'pid-analysis/symbol-detection',
        'pid-analysis/line-detection',
        'pid-analysis/connectivity',
        'pid-analysis/design-checker',
      ],
    },
    {
      type: 'category',
      label: '7. Batch & Delivery',
      link: {type: 'doc', id: 'batch-delivery/index'},
      items: [
        'batch-delivery/batch-processing',
        'batch-delivery/project-management',
        'batch-delivery/export-package',
        'batch-delivery/onboarding-guide',
      ],
    },
    {
      type: 'category',
      label: '8. Quality Assurance',
      link: {type: 'doc', id: 'quality-assurance/index'},
      items: [
        'quality-assurance/gt-comparison',
        'quality-assurance/active-learning',
        'quality-assurance/feedback-pipeline',
        'quality-assurance/ocr-metrics',
        'quality-assurance/evaluation-reports',
      ],
    },
    {
      type: 'category',
      label: '9. Frontend',
      link: {type: 'doc', id: 'frontend/index'},
      items: [
        'frontend/routing',
        'frontend/route-map',
        {
          type: 'category',
          label: '페이지 상세',
          link: {type: 'doc', id: 'frontend/pages/index'},
          collapsed: true,
          items: [
            'frontend/pages/dashboard',
            'frontend/pages/project',
            'frontend/pages/blueprintflow',
            'frontend/pages/session',
            'frontend/pages/admin',
          ],
        },
        'frontend/state-management',
        'frontend/component-library',
        'frontend/bom-frontend',
      ],
    },
    {
      type: 'category',
      label: '10. DevOps',
      link: {type: 'doc', id: 'devops/index'},
      items: [
        'devops/docker-compose',
        'devops/ci-pipeline',
        'devops/cd-pipeline',
        'devops/gpu-config',
      ],
    },
    {
      type: 'category',
      label: '11. R&D Research',
      link: {type: 'doc', id: 'research/index'},
      items: [
        'research/ocr-engineering-drawings',
        'research/edocr2-vision-language',
        'research/geometric-tolerance',
        'research/graph-neural-network',
        'research/yolov11-detection',
        'research/paddleocr',
        'research/trocr-transformer',
        'research/esrgan-super-resolution',
        'research/qwen2-vl',
        'research/graphrag-knowledge',
        'research/tesseract-lstm',
        'research/surya-multilingual',
        'research/doctr-document',
        'research/easyocr',
        'research/ocr-ensemble-voting',
      ],
    },
    {
      type: 'category',
      label: '12. API Reference',
      link: {type: 'doc', id: 'api-reference/index'},
      items: [
        'api-reference/yolo',
        'api-reference/edocr2',
        'api-reference/paddleocr',
        'api-reference/tesseract',
        'api-reference/trocr',
        'api-reference/surya-ocr',
        'api-reference/doctr',
        'api-reference/easyocr',
        'api-reference/ocr-ensemble',
        'api-reference/edgnet',
        'api-reference/line-detector',
        'api-reference/esrgan',
        'api-reference/skinmodel',
        'api-reference/pid-analyzer',
        'api-reference/design-checker',
        'api-reference/blueprint-ai-bom',
        'api-reference/knowledge',
        'api-reference/vl',
      ],
    },
    {
      type: 'category',
      label: '13. Developer Guide',
      link: {type: 'doc', id: 'developer/index'},
      items: [
        'developer/contributing',
        'developer/git-workflow',
        'developer/api-spec-system',
        'developer/dynamic-api-system',
        'developer/llm-usability',
        'developer/api-replacement',
      ],
    },
    {
      type: 'category',
      label: '14. Deployment',
      link: {type: 'doc', id: 'deployment/index'},
      items: [
        'deployment/installation',
        'deployment/on-premise-infra',
        'deployment/on-premise-operation',
        'deployment/admin-manual',
        'deployment/dockerization',
      ],
    },
    {
      type: 'category',
      label: '15. Customer Cases',
      link: {type: 'doc', id: 'customer-cases/index'},
      items: [
        {
          type: 'category',
          label: '동서기연 — 터빈 베어링',
          link: {type: 'doc', id: 'customer-cases/dsebearing/index'},
          collapsed: true,
          items: [
            'customer-cases/dsebearing/data-overview',
            'customer-cases/dsebearing/meeting-history',
            'customer-cases/dsebearing/results',
            'customer-cases/dsebearing/next-steps',
          ],
        },
        'customer-cases/panasia',
      ],
    },
  ],
};

export default sidebars;
