version: '3.8'

services:
  # eDOCr v1
  edocr2-v1:
    image: edocr-api:v1
    container_name: edocr2-api-v1
    ports:
      - "5001:5001"
    volumes:
      - ./uploads:/app/uploads
      - ./results:/app/results
    environment:
      - TF_CPP_MIN_LOG_LEVEL=2
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - poc-network

  # eDOCr v2 (GPU mode - XLA JIT disabled to avoid libdevice issues)
  edocr2-v2:
    image: edocr-api:v2
    container_name: edocr2-api-v2
    ports:
      - "5002:5002"
    volumes:
      - ./models:/app/models:ro  # 모델 공유 (읽기 전용)
      - ./uploads:/app/uploads
      - ./results:/app/results
    environment:
      - TF_CPP_MIN_LOG_LEVEL=2
      - PYTHONUNBUFFERED=1
      - TF_XLA_FLAGS=--tf_xla_enable_xla_devices=false
      - XLA_FLAGS=--xla_gpu_unsafe_fallback_to_driver_on_ptxas_not_found  # Use driver fallback when ptxas not found
      - TF_GPU_ALLOCATOR=cuda_malloc_async  # Better GPU memory management
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/api/v2/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s  # v2는 모델이 더 커서 시작 시간 길어짐
    networks:
      - poc-network

networks:
  poc-network:
    external: true
