version: '3.8'

services:
  edocr2:
    image: edocr-api:v1
    container_name: edocr2-api-v1
    ports:
      - "5001:5001"
    volumes:
      - ./uploads:/app/uploads
      - ./results:/app/results
    environment:
      - TF_CPP_MIN_LOG_LEVEL=2
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - poc-network

networks:
  poc-network:
    external: true
