"""Blueprint AI BOM - Schemas

Pydantic 모델 정의
- Session: 세션 상태 및 정보
- Detection: 검출 결과 및 검증 상태
- Dimension: 치수 OCR 결과 및 검증 (v2 추가)
- AnalysisOptions: 분석 옵션 및 프리셋 (v2 추가)
- Line: 선 검출 및 관계 분석 (v2 추가)
- BOM: BOM 항목 및 내보내기
- Classification: VLM 기반 도면 분류 (Phase 4)
- Relation: 치수선 기반 관계 추출 (Phase 2)
- Region: 영역 분할 (Phase 5)
- GDT: 기하공차 파싱 (Phase 7)
- Feedback: 피드백 루프 파이프라인 (Phase 8)
- Verification: Active Learning 검증 (Phase 8)
"""

from .session import SessionStatus, SessionCreate, SessionResponse, SessionDetail
from .detection import (
    VerificationStatus,
    DetectionConfig,
    BoundingBox,
    Detection,
    DetectionResult,
    VerificationUpdate,
    BulkVerificationUpdate,
    ManualDetection,
)
from .dimension import (
    DimensionType,
    Dimension,
    DimensionCreate,
    DimensionUpdate,
    DimensionResult,
    DimensionListResponse,
    DimensionVerificationUpdate,
    BulkDimensionVerificationUpdate,
)
from .analysis_options import (
    AnalysisOptions,
    AnalysisOptionsUpdate,
    AnalysisResult,
    PRESETS,
    get_preset,
    apply_preset_to_options,
)
from .line import (
    LineType,
    LineStyle,
    Point,
    Line,
    Intersection,
    DimensionLineRelation,
    LineDetectionResult,
    LineDetectionConfig,
    DimensionSymbolLink,
)
from .bom import (
    ExportFormat,
    BOMItem,
    BOMSummary,
    BOMData,
    BOMExportRequest,
    BOMExportResponse,
)
from .classification import (
    DrawingType,
    RegionType,
    DetectedRegionSchema,
    ClassificationRequest,
    ClassificationResultSchema,
    PresetConfig,
    ClassificationWithPresetResponse,
)
from .relation import (
    RelationMethod,
    RelationType,
    DimensionRelationSchema,
    RelationExtractionRequest,
    RelationExtractionResult,
    RelationUpdateRequest,
    BulkRelationUpdateRequest,
    RelationStatistics,
)
from .region import (
    RegionType as SegmentRegionType,  # 기존 classification.RegionType과 구분
    ProcessingStrategy,
    REGION_STRATEGY_MAP,
    Region,
    RegionSegmentationConfig,
    RegionSegmentationRequest,
    RegionSegmentationResult,
    RegionUpdate,
    BulkRegionUpdate,
    ManualRegion,
    RegionProcessingResult,
    TitleBlockData,
    TableCell,
    ParsedTable,
    RegionListResponse,
)
from .gdt import (
    GeometricCharacteristic,
    MaterialCondition,
    GDTCategory,
    CHARACTERISTIC_CATEGORY_MAP,
    CHARACTERISTIC_SYMBOLS,
    CHARACTERISTIC_LABELS,
    DatumReference,
    ToleranceZone,
    FeatureControlFrame,
    DatumFeature,
    GDTParsingConfig,
    GDTParsingRequest,
    GDTParsingResult,
    FCFUpdate,
    BulkFCFUpdate,
    ManualFCF,
    ManualDatum,
    GDTListResponse,
    GDTSummary,
)
from .typed_dicts import (
    PricingInfo,
    BBoxDict,
    DetectionDict,
    DimensionDict,
    SymbolDict,
    LineDict,
    RelationDict,
    SessionMetadata,
    SessionData,
    BOMItemDict,
    BOMSummaryDict,
    HealthResponse,
    ErrorResponse,
    SuccessResponse,
    StatisticsDict,
    VerificationStatsDict,
)
from .feedback import (
    ExportRequest,
    ExportResponse,
    FeedbackStatsResponse,
    SessionStats,
    VerifiedSession,
    VerifiedSessionsResponse,
    ExportInfo,
    ExportListResponse,
    FeedbackHealthResponse,
)
from .verification import (
    VerificationAction,
    BulkApproveRequest,
    ThresholdUpdateRequest,
    VerificationQueueResponse,
    VerificationStatsResponse,
    AutoApproveCandidatesResponse,
    VerificationResultResponse,
    BulkApproveResponse,
    VerificationLogsResponse,
    ThresholdsResponse,
    ThresholdUpdateResponse,
    TrainingDataResponse,
)
from .manufacturing import (
    # 용접 기호 파싱
    WeldingType,
    WeldingLocation,
    WeldingSymbol,
    WeldingParsingResult,
    # 표면 거칠기 파싱
    RoughnessType,
    MachiningMethod,
    LayDirection,
    SurfaceRoughness,
    SurfaceRoughnessResult,
    # 수량 추출
    QuantitySource,
    QuantityItem,
    QuantityExtractionResult,
    # 벌룬 매칭
    BalloonShape,
    Balloon,
    BalloonMatchingResult,
    # 공통
    ManufacturingFeatureResponse,
)
from .longterm import (
    # 도면 영역 세분화
    ViewType,
    DrawingRegion,
    RegionSegmentationConfig as LongtermRegionSegmentationConfig,  # 기존 region.py와 구분
    DrawingRegionSegmentationResult,
    # 주석/노트 추출
    NoteCategory,
    ExtractedNote,
    NotesExtractionConfig,
    NotesExtractionResult,
    # 리비전 비교
    ChangeType,
    ChangeCategory,
    RevisionChange,
    RevisionComparisonConfig,
    RevisionComparisonRequest,
    RevisionComparisonResult,
    # VLM 자동 분류
    DrawingClassification,
    IndustryDomain,
    ComplexityLevel,
    VLMClassificationResult,
    VLMClassificationConfig,
    # 업데이트 모델
    DrawingRegionUpdate,
    ExtractedNoteUpdate,
    LongtermFeatureResponse,
)
from .pid_features import (
    # P&ID 분석 기능
    PIDFeature,
    VerificationStatus as PIDVerificationStatus,
    # Valve Detection
    ValveCategory,
    ValveItem,
    ValveDetectionRequest,
    ValveDetectionResponse,
    # Equipment Detection
    EquipmentType,
    EquipmentItem,
    EquipmentDetectionRequest,
    EquipmentDetectionResponse,
    # Design Checklist
    ChecklistStatus,
    ChecklistItem,
    ChecklistRequest as ChecklistCheckRequest,
    ChecklistResponse as ChecklistCheckResponse,
    # Deviation Analysis
    DeviationCategory,
    DeviationSeverity,
    DeviationSource,
    DeviationItem,
    DeviationAnalysisRequest,
    DeviationAnalysisResponse,
    # Verification
    PIDVerifyRequest,
    PIDBulkVerifyRequest,
    PIDVerificationQueue,
    # Export
    PIDExportRequest,
    PIDExportResponse,
)

__all__ = [
    # Session
    "SessionStatus",
    "SessionCreate",
    "SessionResponse",
    "SessionDetail",
    # Detection
    "VerificationStatus",
    "DetectionConfig",
    "BoundingBox",
    "Detection",
    "DetectionResult",
    "VerificationUpdate",
    "BulkVerificationUpdate",
    "ManualDetection",
    # Dimension (v2)
    "DimensionType",
    "Dimension",
    "DimensionCreate",
    "DimensionUpdate",
    "DimensionResult",
    "DimensionListResponse",
    "DimensionVerificationUpdate",
    "BulkDimensionVerificationUpdate",
    # AnalysisOptions (v2)
    "AnalysisOptions",
    "AnalysisOptionsUpdate",
    "AnalysisResult",
    "PRESETS",
    "get_preset",
    "apply_preset_to_options",
    # Line (v2)
    "LineType",
    "LineStyle",
    "Point",
    "Line",
    "Intersection",
    "DimensionLineRelation",
    "LineDetectionResult",
    "LineDetectionConfig",
    "DimensionSymbolLink",
    # BOM
    "ExportFormat",
    "BOMItem",
    "BOMSummary",
    "BOMData",
    "BOMExportRequest",
    "BOMExportResponse",
    # Classification (Phase 4)
    "DrawingType",
    "RegionType",
    "DetectedRegionSchema",
    "ClassificationRequest",
    "ClassificationResultSchema",
    "PresetConfig",
    "ClassificationWithPresetResponse",
    # Relation (Phase 2)
    "RelationMethod",
    "RelationType",
    "DimensionRelationSchema",
    "RelationExtractionRequest",
    "RelationExtractionResult",
    "RelationUpdateRequest",
    "BulkRelationUpdateRequest",
    "RelationStatistics",
    # Region (Phase 5)
    "SegmentRegionType",
    "ProcessingStrategy",
    "REGION_STRATEGY_MAP",
    "Region",
    "RegionSegmentationConfig",
    "RegionSegmentationRequest",
    "RegionSegmentationResult",
    "RegionUpdate",
    "BulkRegionUpdate",
    "ManualRegion",
    "RegionProcessingResult",
    "TitleBlockData",
    "TableCell",
    "ParsedTable",
    "RegionListResponse",
    # GDT (Phase 7)
    "GeometricCharacteristic",
    "MaterialCondition",
    "GDTCategory",
    "CHARACTERISTIC_CATEGORY_MAP",
    "CHARACTERISTIC_SYMBOLS",
    "CHARACTERISTIC_LABELS",
    "DatumReference",
    "ToleranceZone",
    "FeatureControlFrame",
    "DatumFeature",
    "GDTParsingConfig",
    "GDTParsingRequest",
    "GDTParsingResult",
    "FCFUpdate",
    "BulkFCFUpdate",
    "ManualFCF",
    "ManualDatum",
    "GDTListResponse",
    "GDTSummary",
    # TypedDict (타입 안전성)
    "PricingInfo",
    "BBoxDict",
    "DetectionDict",
    "DimensionDict",
    "SymbolDict",
    "LineDict",
    "RelationDict",
    "SessionMetadata",
    "SessionData",
    "BOMItemDict",
    "BOMSummaryDict",
    "HealthResponse",
    "ErrorResponse",
    "SuccessResponse",
    "StatisticsDict",
    "VerificationStatsDict",
    # Feedback (Phase 8)
    "ExportRequest",
    "ExportResponse",
    "FeedbackStatsResponse",
    "SessionStats",
    "VerifiedSession",
    "VerifiedSessionsResponse",
    "ExportInfo",
    "ExportListResponse",
    "FeedbackHealthResponse",
    # Verification (Phase 8)
    "VerificationAction",
    "BulkApproveRequest",
    "ThresholdUpdateRequest",
    "VerificationQueueResponse",
    "VerificationStatsResponse",
    "AutoApproveCandidatesResponse",
    "VerificationResultResponse",
    "BulkApproveResponse",
    "VerificationLogsResponse",
    "ThresholdsResponse",
    "ThresholdUpdateResponse",
    "TrainingDataResponse",
    # Manufacturing (중기 로드맵)
    "WeldingType",
    "WeldingLocation",
    "WeldingSymbol",
    "WeldingParsingResult",
    "RoughnessType",
    "MachiningMethod",
    "LayDirection",
    "SurfaceRoughness",
    "SurfaceRoughnessResult",
    "QuantitySource",
    "QuantityItem",
    "QuantityExtractionResult",
    "BalloonShape",
    "Balloon",
    "BalloonMatchingResult",
    "ManufacturingFeatureResponse",
    # Longterm (장기 로드맵)
    "ViewType",
    "DrawingRegion",
    "LongtermRegionSegmentationConfig",
    "DrawingRegionSegmentationResult",
    "NoteCategory",
    "ExtractedNote",
    "NotesExtractionConfig",
    "NotesExtractionResult",
    "ChangeType",
    "ChangeCategory",
    "RevisionChange",
    "RevisionComparisonConfig",
    "RevisionComparisonRequest",
    "RevisionComparisonResult",
    "DrawingClassification",
    "IndustryDomain",
    "ComplexityLevel",
    "VLMClassificationResult",
    "VLMClassificationConfig",
    "DrawingRegionUpdate",
    "ExtractedNoteUpdate",
    "LongtermFeatureResponse",
    # P&ID 분석 기능
    "PIDFeature",
    "PIDVerificationStatus",
    "ValveCategory",
    "ValveItem",
    "ValveDetectionRequest",
    "ValveDetectionResponse",
    "EquipmentType",
    "EquipmentItem",
    "EquipmentDetectionRequest",
    "EquipmentDetectionResponse",
    "ChecklistStatus",
    "ChecklistItem",
    "ChecklistCheckRequest",
    "ChecklistCheckResponse",
    # Deviation Analysis
    "DeviationCategory",
    "DeviationSeverity",
    "DeviationSource",
    "DeviationItem",
    "DeviationAnalysisRequest",
    "DeviationAnalysisResponse",
    # Verification & Export
    "PIDVerifyRequest",
    "PIDBulkVerifyRequest",
    "PIDVerificationQueue",
    "PIDExportRequest",
    "PIDExportResponse",
]
