"""
Excel Export
밸브 시그널 리스트 Excel 생성

저자: Claude AI (Opus 4.5)
생성일: 2025-12-29
리팩토링: 2025-12-31
"""
from typing import List, Dict, Any
from datetime import datetime
from io import BytesIO


def generate_valve_signal_excel(
    extracted_items: List[Dict[str, Any]],
    project_info: Dict[str, str] = None,
    rule_name: str = "Valve Signal List"
) -> bytes:
    """
    밸브 시그널 리스트 Excel 생성

    Args:
        extracted_items: 추출된 밸브 항목 목록
        project_info: 프로젝트 정보 (name, drawing_no, date 등)
        rule_name: 규칙 이름

    Returns:
        Excel 파일 바이트 데이터
    """
    try:
        from openpyxl import Workbook
        from openpyxl.styles import Font, Alignment, Border, Side, PatternFill
        from openpyxl.utils import get_column_letter
    except ImportError:
        raise ImportError("openpyxl is required. Install with: pip install openpyxl")

    wb = Workbook()
    ws = wb.active
    ws.title = "Valve Signal List"

    # 스타일 정의
    header_font = Font(bold=True, size=11)
    header_fill = PatternFill(start_color="4472C4", end_color="4472C4", fill_type="solid")
    header_font_white = Font(bold=True, size=11, color="FFFFFF")
    thin_border = Border(
        left=Side(style='thin'),
        right=Side(style='thin'),
        top=Side(style='thin'),
        bottom=Side(style='thin')
    )
    center_align = Alignment(horizontal='center', vertical='center')

    # 제목 행
    current_row = 1
    ws.merge_cells(f'A{current_row}:E{current_row}')
    ws[f'A{current_row}'] = rule_name
    ws[f'A{current_row}'].font = Font(bold=True, size=14)
    ws[f'A{current_row}'].alignment = center_align
    current_row += 1

    # 프로젝트 정보
    if project_info:
        ws.merge_cells(f'A{current_row}:E{current_row}')
        info_text = f"Project: {project_info.get('name', 'N/A')} | Drawing: {project_info.get('drawing_no', 'N/A')} | Date: {project_info.get('date', datetime.now().strftime('%Y-%m-%d'))}"
        ws[f'A{current_row}'] = info_text
        ws[f'A{current_row}'].font = Font(size=10, italic=True)
        current_row += 2
    else:
        current_row += 1

    # 헤더
    headers = ["No.", "Valve ID", "Type", "Category", "Confidence"]
    for col, header in enumerate(headers, 1):
        cell = ws.cell(row=current_row, column=col, value=header)
        cell.font = header_font_white
        cell.fill = header_fill
        cell.border = thin_border
        cell.alignment = center_align
    current_row += 1

    # 데이터
    for idx, item in enumerate(extracted_items, 1):
        valve_id = item.get("id", item.get("matched_text", ""))
        item_type = item.get("type", "unknown")

        # 밸브 카테고리 추론
        category = "Unknown"
        if valve_id.startswith(("BWV", "BAV", "BCV", "BBV", "BXV", "BSV", "BFV", "BRV")):
            category = "BWMS Valve"
        elif valve_id.startswith(("FCV", "TCV", "PCV", "LCV")):
            category = "Control Valve"
        elif valve_id.startswith(("HCV", "SCV", "ACV")):
            category = "Special Valve"

        row_data = [
            idx,
            valve_id,
            item_type.replace("_", " ").title(),
            category,
            f"{item.get('confidence', 1.0):.2f}"
        ]

        for col, value in enumerate(row_data, 1):
            cell = ws.cell(row=current_row, column=col, value=value)
            cell.border = thin_border
            cell.alignment = center_align

        current_row += 1

    # 컬럼 너비 조정
    col_widths = [8, 15, 15, 15, 12]
    for col, width in enumerate(col_widths, 1):
        ws.column_dimensions[get_column_letter(col)].width = width

    # 푸터
    current_row += 1
    ws.merge_cells(f'A{current_row}:E{current_row}')
    ws[f'A{current_row}'] = f"Generated by P&ID Analyzer | Total: {len(extracted_items)} items"
    ws[f'A{current_row}'].font = Font(size=9, italic=True, color="666666")

    # 바이트로 변환
    buffer = BytesIO()
    wb.save(buffer)
    buffer.seek(0)

    return buffer.getvalue()
