import type { TemplateInfo } from './types';

export const basicAdvancedTemplates: TemplateInfo[] = [
  // ============ BASIC TEMPLATES ============
  {
    nameKey: 'speedPipeline',
    descKey: 'speedPipelineDesc',
    useCaseKey: 'speedPipelineUseCase',
    estimatedTime: '8-12s',
    accuracy: '94%',
    category: 'basic',
    workflow: {
      name: 'Speed Pipeline',
      description: 'Fast pipeline with AI BOM Human-in-the-Loop verification',
      nodes: [
        { id: 'imageinput_1', type: 'imageinput', label: 'Image Input', parameters: {}, position: { x: 100, y: 100 } },
        { id: 'yolo_1', type: 'yolo', label: 'YOLO Detection', parameters: { confidence: 0.5, imgsz: 640 }, position: { x: 350, y: 100 } },
        { id: 'aibom_1', type: 'blueprint-ai-bom', label: 'Verification (AI BOM)', parameters: {}, position: { x: 600, y: 100 } },
        { id: 'edocr2_1', type: 'edocr2', label: 'Korean OCR', parameters: {}, position: { x: 850, y: 100 } },
      ],
      edges: [
        { id: 'e1', source: 'imageinput_1', target: 'yolo_1' },
        { id: 'e2', source: 'imageinput_1', target: 'aibom_1' },
        { id: 'e3', source: 'yolo_1', target: 'aibom_1' },
        { id: 'e4', source: 'aibom_1', target: 'edocr2_1' },
      ],
    },
  },
  {
    nameKey: 'basicOCR',
    descKey: 'basicOCRDesc',
    useCaseKey: 'basicOCRUseCase',
    estimatedTime: '10-15s',
    accuracy: '95%',
    category: 'basic',
    workflow: {
      name: 'Basic OCR Pipeline',
      description: 'OCR workflow with AI BOM Human-in-the-Loop and tolerance analysis',
      nodes: [
        { id: 'imageinput_1', type: 'imageinput', label: 'Image Input', parameters: {}, position: { x: 100, y: 100 } },
        { id: 'yolo_1', type: 'yolo', label: 'YOLO Detection', parameters: { confidence: 0.5 }, position: { x: 350, y: 100 } },
        { id: 'aibom_1', type: 'blueprint-ai-bom', label: 'Verification (AI BOM)', parameters: {}, position: { x: 600, y: 100 } },
        { id: 'edocr2_1', type: 'edocr2', label: 'Korean OCR', parameters: {}, position: { x: 850, y: 100 } },
        { id: 'skinmodel_1', type: 'skinmodel', label: 'Tolerance Analysis', parameters: {}, position: { x: 1100, y: 100 } },
      ],
      edges: [
        { id: 'e1', source: 'imageinput_1', target: 'yolo_1' },
        { id: 'e2', source: 'imageinput_1', target: 'aibom_1' },
        { id: 'e3', source: 'yolo_1', target: 'aibom_1' },
        { id: 'e4', source: 'aibom_1', target: 'edocr2_1' },
        { id: 'e5', source: 'edocr2_1', target: 'skinmodel_1' },
      ],
    },
  },

  // ============ ADVANCED TEMPLATES ============
  {
    nameKey: 'accuracyPipeline',
    descKey: 'accuracyPipelineDesc',
    useCaseKey: 'accuracyPipelineUseCase',
    estimatedTime: '15-20s',
    accuracy: '97%',
    category: 'advanced',
    workflow: {
      name: 'Accuracy Pipeline',
      description: 'High accuracy with AI BOM Human-in-the-Loop, dual OCR and segmentation',
      nodes: [
        { id: 'imageinput_1', type: 'imageinput', label: 'Image Input', parameters: {}, position: { x: 100, y: 100 } },
        { id: 'yolo_1', type: 'yolo', label: 'YOLO Detection', parameters: { confidence: 0.35, imgsz: 1280 }, position: { x: 300, y: 100 } },
        { id: 'aibom_1', type: 'blueprint-ai-bom', label: 'Verification (AI BOM)', parameters: {}, position: { x: 500, y: 100 } },
        { id: 'edgnet_1', type: 'edgnet', label: 'Edge Segmentation', parameters: { threshold: 0.5 }, position: { x: 700, y: 100 } },
        { id: 'edocr2_1', type: 'edocr2', label: 'Korean OCR', parameters: {}, position: { x: 900, y: 50 } },
        { id: 'paddleocr_1', type: 'paddleocr', label: 'PaddleOCR', parameters: { lang: 'en' }, position: { x: 900, y: 150 } },
        { id: 'merge_1', type: 'merge', label: 'Merge Results', parameters: {}, position: { x: 1100, y: 100 } },
      ],
      edges: [
        { id: 'e1', source: 'imageinput_1', target: 'yolo_1' },
        { id: 'e2', source: 'imageinput_1', target: 'aibom_1' },
        { id: 'e3', source: 'yolo_1', target: 'aibom_1' },
        { id: 'e4', source: 'aibom_1', target: 'edgnet_1' },
        { id: 'e5', source: 'edgnet_1', target: 'edocr2_1' },
        { id: 'e6', source: 'edgnet_1', target: 'paddleocr_1' },
        { id: 'e7', source: 'edocr2_1', target: 'merge_1' },
        { id: 'e8', source: 'paddleocr_1', target: 'merge_1' },
      ],
    },
  },
  {
    nameKey: 'ocrEnsemble',
    descKey: 'ocrEnsembleDesc',
    useCaseKey: 'ocrEnsembleUseCase',
    estimatedTime: '18-25s',
    accuracy: '98%',
    category: 'advanced',
    workflow: {
      name: 'OCR Ensemble Pipeline',
      description: 'AI BOM Human-in-the-Loop with 4-engine OCR ensemble voting and tolerance analysis',
      nodes: [
        { id: 'imageinput_1', type: 'imageinput', label: 'Image Input', parameters: {}, position: { x: 100, y: 150 } },
        { id: 'esrgan_1', type: 'esrgan', label: 'ESRGAN Upscale', parameters: { scale: 2 }, position: { x: 300, y: 150 } },
        { id: 'yolo_1', type: 'yolo', label: 'YOLO Detection', parameters: { confidence: 0.3, imgsz: 1280 }, position: { x: 500, y: 150 } },
        { id: 'aibom_1', type: 'blueprint-ai-bom', label: 'Verification (AI BOM)', parameters: {}, position: { x: 700, y: 150 } },
        { id: 'ocr_ensemble_1', type: 'ocr_ensemble', label: 'OCR Ensemble (4-way)', parameters: {}, position: { x: 950, y: 50 } },
        { id: 'edocr2_1', type: 'edocr2', label: 'Dimension OCR', parameters: {}, position: { x: 950, y: 250 } },
        { id: 'skinmodel_1', type: 'skinmodel', label: 'Tolerance Analysis', parameters: {}, position: { x: 1200, y: 250 } },
      ],
      edges: [
        { id: 'e1', source: 'imageinput_1', target: 'esrgan_1' },
        { id: 'e2', source: 'esrgan_1', target: 'yolo_1' },
        { id: 'e3', source: 'esrgan_1', target: 'aibom_1' },
        { id: 'e4', source: 'yolo_1', target: 'aibom_1' },
        { id: 'e5', source: 'aibom_1', target: 'ocr_ensemble_1' },
        { id: 'e6', source: 'aibom_1', target: 'edocr2_1' },
        { id: 'e7', source: 'edocr2_1', target: 'skinmodel_1' },
      ],
    },
  },
  {
    nameKey: 'multiOCRComparison',
    descKey: 'multiOCRComparisonDesc',
    useCaseKey: 'multiOCRComparisonUseCase',
    estimatedTime: '18-25s',
    accuracy: '96%',
    category: 'advanced',
    workflow: {
      name: 'Multi-OCR Comparison',
      description: 'AI BOM Human-in-the-Loop with 4 OCR engine comparison',
      nodes: [
        { id: 'imageinput_1', type: 'imageinput', label: 'Image Input', parameters: {}, position: { x: 100, y: 200 } },
        { id: 'yolo_1', type: 'yolo', label: 'YOLO Detection', parameters: { confidence: 0.4 }, position: { x: 300, y: 200 } },
        { id: 'aibom_1', type: 'blueprint-ai-bom', label: 'Verification (AI BOM)', parameters: {}, position: { x: 500, y: 200 } },
        { id: 'edocr2_1', type: 'edocr2', label: 'eDOCr2', parameters: {}, position: { x: 750, y: 80 } },
        { id: 'paddleocr_1', type: 'paddleocr', label: 'PaddleOCR', parameters: {}, position: { x: 750, y: 160 } },
        { id: 'tesseract_1', type: 'tesseract', label: 'Tesseract', parameters: {}, position: { x: 750, y: 240 } },
        { id: 'easyocr_1', type: 'easyocr', label: 'EasyOCR', parameters: { languages: ['en'] }, position: { x: 750, y: 320 } },
        { id: 'merge_1', type: 'merge', label: 'Compare & Merge', parameters: {}, position: { x: 1000, y: 200 } },
      ],
      edges: [
        { id: 'e1', source: 'imageinput_1', target: 'yolo_1' },
        { id: 'e2', source: 'imageinput_1', target: 'aibom_1' },
        { id: 'e3', source: 'yolo_1', target: 'aibom_1' },
        { id: 'e4', source: 'aibom_1', target: 'edocr2_1' },
        { id: 'e5', source: 'aibom_1', target: 'paddleocr_1' },
        { id: 'e6', source: 'aibom_1', target: 'tesseract_1' },
        { id: 'e7', source: 'aibom_1', target: 'easyocr_1' },
        { id: 'e8', source: 'edocr2_1', target: 'merge_1' },
        { id: 'e9', source: 'paddleocr_1', target: 'merge_1' },
        { id: 'e10', source: 'tesseract_1', target: 'merge_1' },
        { id: 'e11', source: 'easyocr_1', target: 'merge_1' },
      ],
    },
  },

  // ============ CONTROL FLOW TEMPLATES ============
  {
    nameKey: 'conditionalOCR',
    descKey: 'conditionalOCRDesc',
    useCaseKey: 'conditionalOCRUseCase',
    estimatedTime: '12-18s',
    accuracy: '96%',
    category: 'advanced',
    workflow: {
      name: 'Conditional OCR Pipeline',
      description: 'AI BOM Human-in-the-Loop with intelligent branching based on detection confidence',
      nodes: [
        { id: 'imageinput_1', type: 'imageinput', label: 'Image Input', parameters: {}, position: { x: 100, y: 150 } },
        { id: 'yolo_1', type: 'yolo', label: 'YOLO Detection', parameters: { confidence: 0.5 }, position: { x: 300, y: 150 } },
        { id: 'aibom_1', type: 'blueprint-ai-bom', label: 'Verification (AI BOM)', parameters: {}, position: { x: 500, y: 150 } },
        { id: 'if_1', type: 'if', label: 'Check Confidence', parameters: { condition: 'confidence > 0.8' }, position: { x: 700, y: 150 } },
        { id: 'edocr2_1', type: 'edocr2', label: 'eDOCr2 (High Conf)', parameters: {}, position: { x: 900, y: 80 } },
        { id: 'ocr_ensemble_1', type: 'ocr_ensemble', label: 'OCR Ensemble (Low Conf)', parameters: {}, position: { x: 900, y: 220 } },
        { id: 'merge_1', type: 'merge', label: 'Merge Results', parameters: {}, position: { x: 1150, y: 150 } },
      ],
      edges: [
        { id: 'e1', source: 'imageinput_1', target: 'yolo_1' },
        { id: 'e2', source: 'imageinput_1', target: 'aibom_1' },
        { id: 'e3', source: 'yolo_1', target: 'aibom_1' },
        { id: 'e4', source: 'aibom_1', target: 'if_1' },
        { id: 'e5', source: 'if_1', target: 'edocr2_1', sourceHandle: 'true' },
        { id: 'e6', source: 'if_1', target: 'ocr_ensemble_1', sourceHandle: 'false' },
        { id: 'e7', source: 'edocr2_1', target: 'merge_1' },
        { id: 'e8', source: 'ocr_ensemble_1', target: 'merge_1' },
      ],
    },
  },
  {
    nameKey: 'loopDetection',
    descKey: 'loopDetectionDesc',
    useCaseKey: 'loopDetectionUseCase',
    estimatedTime: '20-30s',
    accuracy: '98%',
    category: 'advanced',
    workflow: {
      name: 'Loop Detection Pipeline',
      description: 'AI BOM Human-in-the-Loop with iterative processing for maximum accuracy',
      nodes: [
        { id: 'imageinput_1', type: 'imageinput', label: 'Image Input', parameters: {}, position: { x: 100, y: 150 } },
        { id: 'yolo_1', type: 'yolo', label: 'YOLO Detection', parameters: { confidence: 0.35 }, position: { x: 300, y: 150 } },
        { id: 'aibom_1', type: 'blueprint-ai-bom', label: 'Verification (AI BOM)', parameters: {}, position: { x: 500, y: 150 } },
        { id: 'loop_1', type: 'loop', label: 'For Each Detection', parameters: { iterator: 'detections' }, position: { x: 700, y: 150 } },
        { id: 'edocr2_1', type: 'edocr2', label: 'OCR Each Box', parameters: {}, position: { x: 900, y: 150 } },
        { id: 'skinmodel_1', type: 'skinmodel', label: 'Tolerance Analysis', parameters: {}, position: { x: 1100, y: 150 } },
      ],
      edges: [
        { id: 'e1', source: 'imageinput_1', target: 'yolo_1' },
        { id: 'e2', source: 'imageinput_1', target: 'aibom_1' },
        { id: 'e3', source: 'yolo_1', target: 'aibom_1' },
        { id: 'e4', source: 'aibom_1', target: 'loop_1' },
        { id: 'e5', source: 'loop_1', target: 'edocr2_1' },
        { id: 'e6', source: 'edocr2_1', target: 'skinmodel_1' },
      ],
    },
  },
];
