import type { TemplateInfo } from './types';

export const dseBearingTemplates: TemplateInfo[] = [
  // ============ DSE BEARING TEMPLATES ============
  {
    nameKey: 'dseBearingAnalysis',
    descKey: 'dseBearingAnalysisDesc',
    useCaseKey: 'dseBearingAnalysisUseCase',
    estimatedTime: '15-25s',
    accuracy: '96%',
    category: 'dsebearing',
    featured: true,
    sampleImage: '/samples/dse_bearing_assy_t1.png',
    workflow: {
      name: 'DSE Bearing 1-1: 단품 도면 분석 + AI BOM',
      description: '터빈 베어링 단품 부품도 분석 - Table Detector로 BOM 테이블 추출, 치수 OCR, 견적용 BOM 생성 (소재 사이즈 1순위)',
      nodes: [
        { id: 'imageinput_1', type: 'imageinput', label: '부품도 입력', parameters: { features: ['dimension_ocr', 'table_extraction'] }, position: { x: 100, y: 200 } },
        { id: 'tabledetector_1', type: 'table_detector', label: 'BOM 테이블 추출', parameters: { mode: 'extract', ocr_engine: 'paddle', borderless: false, confidence_threshold: 0.5, min_confidence: 50, crop_regions: ['title_block', 'revision_table', 'parts_list_right'], enable_quality_filter: true }, position: { x: 350, y: 100 } },
        { id: 'edocr2_1', type: 'edocr2', label: '치수/텍스트 OCR', parameters: { extract_dimensions: true, extract_gdt: false, language: 'ko+en', enable_crop_upscale: true, crop_preset: 'quadrants', upscale_scale: 2, upscale_denoise: 0.3 }, position: { x: 350, y: 300 } },
        { id: 'aibom_1', type: 'blueprint-ai-bom', label: '도면 검증 (AI BOM)', parameters: { drawing_type: 'dimension_bom', features: ['table_extraction', 'human_verification'] }, position: { x: 600, y: 100 } },
        { id: 'dim_updater_1', type: 'dimension_updater', label: '치수 비동기 추가', parameters: {}, position: { x: 600, y: 350 } },
      ],
      edges: [
        { id: 'e1', source: 'imageinput_1', target: 'tabledetector_1' },
        { id: 'e2', source: 'imageinput_1', target: 'edocr2_1' },
        { id: 'e3', source: 'imageinput_1', target: 'aibom_1' },
        { id: 'e4', source: 'tabledetector_1', target: 'aibom_1' },
        { id: 'e5', source: 'aibom_1', target: 'dim_updater_1' },
        { id: 'e6', source: 'edocr2_1', target: 'dim_updater_1' },
      ],
    },
  },
  {
    nameKey: 'dseBearingRingAssy',
    descKey: 'dseBearingRingAssyDesc',
    useCaseKey: 'dseBearingRingAssyUseCase',
    estimatedTime: '25-35s',
    accuracy: '94%',
    category: 'dsebearing',
    hidden: true,
    sampleImage: '/samples/dse_ring_assy_t1.png',
    workflow: {
      name: 'DSE Bearing 2-1: Bearing Ring ASSY',
      description: 'Tilting Pad(T1-T3)/Elliptical(T4-T8) 베어링 링 조립체 - Table Detector로 BOM 추출 + Babbitt 라이닝 틈새 분석',
      nodes: [
        { id: 'imageinput_1', type: 'imageinput', label: 'Ring ASSY 도면', parameters: { features: ['dimension_ocr', 'dimension_verification', 'gt_comparison'] }, position: { x: 100, y: 200 } },
        { id: 'esrgan_1', type: 'esrgan', label: '이미지 향상', parameters: { scale: 2 }, position: { x: 300, y: 200 } },
        { id: 'tabledetector_1', type: 'table_detector', label: 'BOM 테이블 추출', parameters: { mode: 'extract', ocr_engine: 'paddle', borderless: false, confidence_threshold: 0.5, min_confidence: 50, crop_regions: ['title_block', 'revision_table', 'parts_list_right'], enable_quality_filter: true }, position: { x: 500, y: 100 } },
        { id: 'edocr2_1', type: 'edocr2', label: '치수/공차 OCR', parameters: { extract_dimensions: true, extract_gdt: true, extract_tables: true }, position: { x: 500, y: 300 } },
        { id: 'aibom_1', type: 'blueprint-ai-bom', label: 'BOM 검증 (AI BOM)', parameters: { drawing_type: 'assembly', features: ['table_extraction', 'dimension_verification'] }, position: { x: 750, y: 100 } },
        { id: 'dim_updater_1', type: 'dimension_updater', label: '치수 비동기 추가', parameters: {}, position: { x: 750, y: 350 } },
        { id: 'skinmodel_1', type: 'skinmodel', label: '틈새 공차 분석', parameters: { task: 'tolerance', material_type: 'steel', correlation_length: 2.0 }, position: { x: 1000, y: 200 } },
      ],
      edges: [
        { id: 'e1', source: 'imageinput_1', target: 'esrgan_1' },
        { id: 'e2', source: 'esrgan_1', target: 'tabledetector_1' },
        { id: 'e3', source: 'esrgan_1', target: 'edocr2_1' },
        { id: 'e4', source: 'imageinput_1', target: 'aibom_1' },
        { id: 'e5', source: 'tabledetector_1', target: 'aibom_1' },
        { id: 'e6', source: 'aibom_1', target: 'dim_updater_1' },
        { id: 'e7', source: 'edocr2_1', target: 'dim_updater_1' },
        { id: 'e8', source: 'dim_updater_1', target: 'skinmodel_1' },
      ],
    },
  },
  {
    nameKey: 'dseBearingCasingAssy',
    descKey: 'dseBearingCasingAssyDesc',
    useCaseKey: 'dseBearingCasingAssyUseCase',
    estimatedTime: '25-35s',
    sampleImage: '/samples/dse_casing_assy_t1.png',
    accuracy: '93%',
    category: 'dsebearing',
    hidden: true,
    workflow: {
      name: 'DSE Bearing 2-2: Bearing Casing ASSY',
      description: '베어링 케이싱 조립체 - Table Detector + VLM으로 상하부 Split 구조, 오일 포트/나사 가공 추출',
      nodes: [
        { id: 'imageinput_1', type: 'imageinput', label: 'Casing ASSY 도면', parameters: { features: ['dimension_ocr', 'dimension_verification', 'gt_comparison'] }, position: { x: 100, y: 200 } },
        { id: 'esrgan_1', type: 'esrgan', label: '이미지 향상', parameters: { scale: 2 }, position: { x: 300, y: 200 } },
        { id: 'tabledetector_1', type: 'table_detector', label: 'BOM 테이블 추출', parameters: { mode: 'extract', ocr_engine: 'paddle', borderless: false, confidence_threshold: 0.5, min_confidence: 50, crop_regions: ['title_block', 'revision_table', 'parts_list_right'], enable_quality_filter: true }, position: { x: 500, y: 100 } },
        { id: 'edocr2_1', type: 'edocr2', label: '나사/포트 OCR', parameters: { extract_dimensions: true, extract_text: true, language: 'ko+en' }, position: { x: 500, y: 300 } },
        { id: 'aibom_1', type: 'blueprint-ai-bom', label: 'Casing 검증', parameters: { drawing_type: 'assembly', features: ['table_extraction', 'dimension_verification'] }, position: { x: 750, y: 100 } },
        { id: 'dim_updater_1', type: 'dimension_updater', label: '치수 비동기 추가', parameters: {}, position: { x: 750, y: 350 } },
        { id: 'skinmodel_1', type: 'skinmodel', label: '가공 난이도 분석', parameters: { task: 'manufacturability', material_type: 'steel', manufacturing_process: 'machining' }, position: { x: 1000, y: 200 } },
      ],
      edges: [
        { id: 'e1', source: 'imageinput_1', target: 'esrgan_1' },
        { id: 'e2', source: 'esrgan_1', target: 'tabledetector_1' },
        { id: 'e3', source: 'esrgan_1', target: 'edocr2_1' },
        { id: 'e4', source: 'imageinput_1', target: 'aibom_1' },
        { id: 'e5', source: 'tabledetector_1', target: 'aibom_1' },
        { id: 'e6', source: 'aibom_1', target: 'dim_updater_1' },
        { id: 'e7', source: 'edocr2_1', target: 'dim_updater_1' },
        { id: 'e8', source: 'dim_updater_1', target: 'skinmodel_1' },
      ],
    },
  },
  {
    nameKey: 'dseThrustBearing',
    descKey: 'dseThrustBearingDesc',
    useCaseKey: 'dseThrustBearingUseCase',
    estimatedTime: '30-40s',
    accuracy: '95%',
    category: 'dsebearing',
    hidden: true,
    sampleImage: '/samples/dse_thrust_bearing_assy.png',
    workflow: {
      name: 'DSE Bearing 2-3: Thrust Bearing',
      description: '스러스트 베어링 조립체 (TBN/GEN Side) - Table Detector + VLM으로 12개 PAD, Leveling Plate, PIVOT 분석',
      nodes: [
        { id: 'imageinput_1', type: 'imageinput', label: 'Thrust Bearing 도면', parameters: { features: ['dimension_ocr', 'dimension_verification', 'gt_comparison'] }, position: { x: 100, y: 200 } },
        { id: 'esrgan_1', type: 'esrgan', label: '이미지 향상', parameters: { scale: 2 }, position: { x: 300, y: 100 } },
        { id: 'vl_1', type: 'vl', label: 'VLM 구조 분석', parameters: { prompt: '스러스트 베어링의 PAD 배열, 상하부 케이싱 구조, 레벨링 플레이트 배치를 분석해주세요' }, position: { x: 300, y: 350 } },
        { id: 'tabledetector_1', type: 'table_detector', label: 'BOM 테이블 추출', parameters: { mode: 'extract', ocr_engine: 'paddle', borderless: false, confidence_threshold: 0.5, min_confidence: 50, crop_regions: ['title_block', 'revision_table', 'parts_list_right'], enable_quality_filter: true }, position: { x: 550, y: 50 } },
        { id: 'edocr2_1', type: 'edocr2', label: '치수/토크 OCR', parameters: { extract_dimensions: true, extract_text: true, extract_tables: true }, position: { x: 550, y: 300 } },
        { id: 'aibom_1', type: 'blueprint-ai-bom', label: 'Thrust BOM 검증', parameters: { drawing_type: 'assembly', features: ['table_extraction', 'dimension_verification', 'human_verification'] }, position: { x: 800, y: 100 } },
        { id: 'dim_updater_1', type: 'dimension_updater', label: '치수 비동기 추가', parameters: {}, position: { x: 800, y: 350 } },
        { id: 'skinmodel_1', type: 'skinmodel', label: 'PAD 틈새 분석', parameters: { task: 'tolerance', material_type: 'steel', correlation_length: 1.5 }, position: { x: 1050, y: 200 } },
        { id: 'merge_1', type: 'merge', label: '분석 통합', parameters: {}, position: { x: 1250, y: 200 } },
      ],
      edges: [
        { id: 'e1', source: 'imageinput_1', target: 'esrgan_1' },
        { id: 'e2', source: 'imageinput_1', target: 'vl_1' },
        { id: 'e3', source: 'esrgan_1', target: 'tabledetector_1' },
        { id: 'e4', source: 'esrgan_1', target: 'edocr2_1' },
        { id: 'e5', source: 'imageinput_1', target: 'aibom_1' },
        { id: 'e6', source: 'tabledetector_1', target: 'aibom_1' },
        { id: 'e7', source: 'aibom_1', target: 'dim_updater_1' },
        { id: 'e8', source: 'edocr2_1', target: 'dim_updater_1' },
        { id: 'e9', source: 'dim_updater_1', target: 'skinmodel_1' },
        { id: 'e10', source: 'vl_1', target: 'merge_1' },
        { id: 'e11', source: 'skinmodel_1', target: 'merge_1' },
      ],
    },
  },
  {
    nameKey: 'dseBearingYoloPartsListExtract',
    descKey: 'dseBearingYoloPartsListExtractDesc',
    useCaseKey: 'dseBearingYoloPartsListExtractUseCase',
    estimatedTime: '15-25s',
    accuracy: '98%',
    category: 'dsebearing',
    sampleImage: '/samples/dse_bearing_assy_t1.png',
    featured: true,
    workflow: {
      name: 'DSE Bearing 2-8: YOLO 기반 Parts List 추출',
      description: 'YOLO로 text_block 영역 검출 후 Table Detector로 테이블 구조 추출 - TATR 검출 한계 극복',
      nodes: [
        { id: 'imageinput_1', type: 'imageinput', label: '도면 입력', parameters: { features: ['dimension_ocr'] }, position: { x: 100, y: 200 } },
        { id: 'yolo_1', type: 'yolo', label: 'Parts List 영역 검출', parameters: { model_type: 'drawing', confidence: 0.35, iou: 0.45, imgsz: 1280, classes: ['text_block'] }, position: { x: 350, y: 200 } },
        { id: 'table_detector_1', type: 'table_detector', label: '테이블 구조 추출', parameters: { mode: 'extract', ocr_engine: 'paddle', borderless: false, confidence_threshold: 0.5, min_confidence: 50, crop_regions: ['title_block', 'revision_table', 'parts_list_right'], enable_quality_filter: true }, position: { x: 600, y: 200 } },
        { id: 'aibom_1', type: 'blueprint-ai-bom', label: 'Parts List 검증 (AI BOM)', parameters: { drawing_type: 'dimension_bom', features: ['table_extraction', 'human_verification'] }, position: { x: 850, y: 200 } },
      ],
      edges: [
        { id: 'e1', source: 'imageinput_1', target: 'yolo_1' },
        { id: 'e2', source: 'yolo_1', target: 'table_detector_1' },
        { id: 'e3', source: 'imageinput_1', target: 'aibom_1' },
        { id: 'e4', source: 'table_detector_1', target: 'aibom_1' },
      ],
    },
  },
  {
    nameKey: 'dseBearingFullQuote',
    descKey: 'dseBearingFullQuoteDesc',
    useCaseKey: 'dseBearingFullQuoteUseCase',
    estimatedTime: '35-45s',
    accuracy: '96%',
    category: 'dsebearing',
    sampleImage: '/samples/dse_bearing_assy_t1.png',
    featured: true,
    workflow: {
      name: 'DSE Bearing 3-2: 완전 자동 견적',
      description: 'Title Block → Parts List → Dimension → BOM Matcher → Quote Generator → Excel 견적서 자동 생성',
      nodes: [
        { id: 'imageinput_1', type: 'imageinput', label: '베어링 도면 입력', parameters: { features: ['dimension_ocr', 'dimension_verification', 'gt_comparison'] }, position: { x: 100, y: 200 } },
        { id: 'titleblock_1', type: 'titleblock', label: 'Title Block 파싱', parameters: { detection_method: 'auto', title_block_position: 'bottom_right', ocr_engine: 'paddle', company_template: 'doosan', profile: 'bearing' }, position: { x: 350, y: 100 } },
        { id: 'partslist_1', type: 'partslist', label: 'Parts List 파싱', parameters: { table_position: 'auto', ocr_engine: 'paddle', normalize_material: true, normalize_headers: true, profile: 'bearing' }, position: { x: 350, y: 300 } },
        { id: 'edocr2_1', type: 'edocr2', label: '치수 OCR', parameters: { extract_dimensions: true, extract_gdt: true }, position: { x: 600, y: 200 } },
        { id: 'dimensionparser_1', type: 'dimensionparser', label: '치수 파싱', parameters: { dimension_type: 'bearing', parse_tolerance: true, parse_gdt: true, extract_od_id: true }, position: { x: 850, y: 200 } },
        { id: 'aibom_1', type: 'blueprint-ai-bom', label: 'BOM 세션 생성 (AI BOM)', parameters: { drawing_type: 'assembly', features: ['table_extraction', 'dimension_verification', 'bom_generation'] }, position: { x: 850, y: 400 } },
        { id: 'bommatcher_1', type: 'bommatcher', label: 'BOM 통합 + 견적', parameters: { match_strategy: 'hybrid', confidence_threshold: 0.7, include_dimensions: true, validate_material: true, generate_quote: true, customer_id: 'DSE', material_markup: 1.3, labor_markup: 1.5 }, position: { x: 1100, y: 200 } },
        { id: 'quotegenerator_1', type: 'quotegenerator', label: '견적서 출력', parameters: { currency: 'KRW', tax_rate: 10, quantity_discount: true }, position: { x: 1350, y: 200 } },
      ],
      edges: [
        { id: 'e1', source: 'imageinput_1', target: 'titleblock_1' },
        { id: 'e2', source: 'imageinput_1', target: 'partslist_1' },
        { id: 'e3', source: 'imageinput_1', target: 'edocr2_1' },
        { id: 'e4', source: 'edocr2_1', target: 'dimensionparser_1' },
        { id: 'e5', source: 'titleblock_1', target: 'bommatcher_1' },
        { id: 'e6', source: 'partslist_1', target: 'bommatcher_1' },
        { id: 'e7', source: 'dimensionparser_1', target: 'bommatcher_1' },
        { id: 'e8', source: 'bommatcher_1', target: 'quotegenerator_1' },
        { id: 'e9', source: 'imageinput_1', target: 'aibom_1' },
        { id: 'e10', source: 'edocr2_1', target: 'aibom_1' },
      ],
    },
  },
];
