import type { TemplateInfo } from './types';

export const templates: TemplateInfo[] = [
  // ============ FEATURED TEMPLATES ============
  {
    nameKey: 'completeAnalysis',
    descKey: 'completeAnalysisDesc',
    useCaseKey: 'completeAnalysisUseCase',
    estimatedTime: '30-40s',
    accuracy: '98%',
    category: 'advanced',
    featured: true,
    workflow: {
      name: 'Complete Drawing Analysis',
      description: 'Full analysis with AI BOM Human-in-the-Loop, detection, OCR, tolerance analysis, and AI description',
      nodes: [
        { id: 'imageinput_1', type: 'imageinput', label: 'Drawing Input', parameters: {}, position: { x: 100, y: 200 } },
        { id: 'esrgan_1', type: 'esrgan', label: 'Image Enhancement', parameters: { scale: 2 }, position: { x: 300, y: 200 } },
        { id: 'yolo_1', type: 'yolo', label: 'Symbol Detection', parameters: { confidence: 0.35, imgsz: 1280 }, position: { x: 500, y: 100 } },
        { id: 'aibom_1', type: 'blueprint-ai-bom', label: 'Symbol Verification (AI BOM)', parameters: {}, position: { x: 700, y: 100 } },
        { id: 'edgnet_1', type: 'edgnet', label: 'Segmentation', parameters: { threshold: 0.5 }, position: { x: 500, y: 300 } },
        { id: 'edocr2_1', type: 'edocr2', label: 'Dimension OCR', parameters: {}, position: { x: 750, y: 300 } },
        { id: 'ocr_ensemble_1', type: 'ocr_ensemble', label: 'OCR Ensemble', parameters: {}, position: { x: 900, y: 100 } },
        { id: 'skinmodel_1', type: 'skinmodel', label: 'Tolerance Analysis', parameters: {}, position: { x: 950, y: 300 } },
        { id: 'vl_1', type: 'vl', label: 'AI Description', parameters: { prompt: 'Describe this engineering drawing' }, position: { x: 1100, y: 150 } },
        { id: 'merge_1', type: 'merge', label: 'Final Results', parameters: {}, position: { x: 1300, y: 200 } },
      ],
      edges: [
        { id: 'e1', source: 'imageinput_1', target: 'esrgan_1' },
        { id: 'e2', source: 'esrgan_1', target: 'yolo_1' },
        { id: 'e3', source: 'esrgan_1', target: 'edgnet_1' },
        { id: 'e4', source: 'esrgan_1', target: 'aibom_1' },
        { id: 'e5', source: 'yolo_1', target: 'aibom_1' },
        { id: 'e6', source: 'aibom_1', target: 'ocr_ensemble_1' },
        { id: 'e7', source: 'edgnet_1', target: 'edocr2_1' },
        { id: 'e8', source: 'edocr2_1', target: 'skinmodel_1' },
        { id: 'e9', source: 'ocr_ensemble_1', target: 'vl_1' },
        { id: 'e10', source: 'skinmodel_1', target: 'vl_1' },
        { id: 'e11', source: 'vl_1', target: 'merge_1' },
      ],
    },
  },
  {
    nameKey: 'pidAnalysis',
    descKey: 'pidAnalysisDesc',
    useCaseKey: 'pidAnalysisUseCase',
    estimatedTime: '25-35s',
    accuracy: '96%',
    category: 'pid',
    featured: true,
    workflow: {
      name: 'P&ID Analysis Pipeline',
      description: 'Complete P&ID analysis with AI BOM Human-in-the-Loop, symbol detection, line detection, connectivity analysis',
      nodes: [
        { id: 'imageinput_1', type: 'imageinput', label: 'P&ID Image Input', parameters: {}, position: { x: 100, y: 200 } },
        { id: 'yolo_1', type: 'yolo', label: 'YOLO P&ID Symbol Detection', parameters: { model_type: 'pid_class_aware', confidence: 0.25, iou: 0.45, imgsz: 640, use_sahi: true }, position: { x: 350, y: 100 } },
        { id: 'aibom_1', type: 'blueprint-ai-bom', label: 'Symbol Verification (AI BOM)', parameters: {}, position: { x: 600, y: 100 } },
        { id: 'linedetector_1', type: 'linedetector', label: 'Line Detector', parameters: { method: 'lsd', min_length: 50, merge_lines: true, classify_types: true }, position: { x: 350, y: 300 } },
        { id: 'pidanalyzer_1', type: 'pidanalyzer', label: 'P&ID Analyzer', parameters: { generate_bom: true, generate_valve_list: true, generate_equipment_list: true }, position: { x: 850, y: 200 } },
        { id: 'designchecker_1', type: 'designchecker', label: 'Design Checker', parameters: { severity_threshold: 'warning' }, position: { x: 1100, y: 200 } },
      ],
      edges: [
        { id: 'e1', source: 'imageinput_1', target: 'yolo_1' },
        { id: 'e2', source: 'imageinput_1', target: 'aibom_1' },
        { id: 'e3', source: 'yolo_1', target: 'aibom_1' },
        { id: 'e4', source: 'imageinput_1', target: 'linedetector_1' },
        { id: 'e5', source: 'aibom_1', target: 'pidanalyzer_1' },
        { id: 'e6', source: 'linedetector_1', target: 'pidanalyzer_1' },
        { id: 'e7', source: 'pidanalyzer_1', target: 'designchecker_1' },
      ],
    },
  },

  // ============ TECHCROSS TEMPLATES ============
  {
    nameKey: 'techcrossBwmsChecklist',
    descKey: 'techcrossBwmsChecklistDesc',
    useCaseKey: 'techcrossBwmsChecklistUseCase',
    estimatedTime: '15-25s',
    accuracy: '97%',
    category: 'techcross',
    featured: true,
    workflow: {
      name: 'TECHCROSS 1-1: BWMS Checklist',
      description: 'BWMS P&ID 체크리스트 검증 - AI BOM Human-in-the-Loop, 58개 ECS 규칙, 84% 노이즈 제거',
      nodes: [
        { id: 'imageinput_1', type: 'imageinput', label: 'P&ID 도면 입력', parameters: {}, position: { x: 100, y: 200 } },
        { id: 'yolo_1', type: 'yolo', label: 'P&ID 심볼 검출', parameters: { model_type: 'pid_class_aware', confidence: 0.25, iou: 0.45, imgsz: 640, use_sahi: true }, position: { x: 350, y: 200 } },
        { id: 'aibom_1', type: 'blueprint-ai-bom', label: '심볼 검증 (AI BOM)', parameters: {}, position: { x: 600, y: 200 } },
        { id: 'linedetector_1', type: 'linedetector', label: '라인 검출', parameters: { method: 'lsd', min_length: 50, classify_types: true, classify_colors: true }, position: { x: 600, y: 350 } },
        { id: 'pidanalyzer_1', type: 'pidanalyzer', label: '연결성 분석', parameters: { generate_bom: false, generate_valve_list: false, generate_equipment_list: false }, position: { x: 850, y: 350 } },
        { id: 'designchecker_1', type: 'designchecker', label: 'BWMS 체크리스트', parameters: { rule_profile: 'bwms', product_type: 'ECS', severity_threshold: 'warning' }, position: { x: 1100, y: 200 } },
      ],
      edges: [
        { id: 'e1', source: 'imageinput_1', target: 'yolo_1' },
        { id: 'e2', source: 'imageinput_1', target: 'aibom_1' },
        { id: 'e3', source: 'yolo_1', target: 'aibom_1' },
        { id: 'e4', source: 'imageinput_1', target: 'linedetector_1' },
        { id: 'e5', source: 'aibom_1', target: 'pidanalyzer_1' },
        { id: 'e6', source: 'linedetector_1', target: 'pidanalyzer_1' },
        { id: 'e7', source: 'aibom_1', target: 'designchecker_1' },
        { id: 'e8', source: 'pidanalyzer_1', target: 'designchecker_1' },
      ],
    },
  },
  {
    nameKey: 'techcrossValveSignal',
    descKey: 'techcrossValveSignalDesc',
    useCaseKey: 'techcrossValveSignalUseCase',
    estimatedTime: '15-25s',
    accuracy: '96%',
    category: 'techcross',
    workflow: {
      name: 'TECHCROSS 1-2: Valve Signal List',
      description: '밸브 신호 목록 생성 - AI BOM Human-in-the-Loop, Control/Isolation/Safety/Check/Relief 분류',
      nodes: [
        { id: 'imageinput_1', type: 'imageinput', label: 'P&ID 도면 입력', parameters: { features: ['symbol_detection', 'symbol_verification', 'gt_comparison'] }, position: { x: 100, y: 200 } },
        { id: 'yolo_1', type: 'yolo', label: 'P&ID 심볼 검출', parameters: { model_type: 'pid_class_aware', confidence: 0.25, iou: 0.45, imgsz: 640, use_sahi: true }, position: { x: 350, y: 200 } },
        { id: 'aibom_1', type: 'blueprint-ai-bom', label: '밸브 검증 (AI BOM)', parameters: {}, position: { x: 600, y: 200 } },
        { id: 'pidfeatures_1', type: 'pidfeatures', label: '밸브 신호 분석', parameters: { detect_valves: true, detect_equipment: false, classify_valve_types: true }, position: { x: 850, y: 200 } },
      ],
      edges: [
        { id: 'e1', source: 'imageinput_1', target: 'yolo_1' },
        { id: 'e2', source: 'imageinput_1', target: 'aibom_1' },
        { id: 'e3', source: 'yolo_1', target: 'aibom_1' },
        { id: 'e4', source: 'aibom_1', target: 'pidfeatures_1' },
      ],
    },
  },
  {
    nameKey: 'techcrossEquipmentList',
    descKey: 'techcrossEquipmentListDesc',
    useCaseKey: 'techcrossEquipmentListUseCase',
    estimatedTime: '15-25s',
    accuracy: '93%',
    category: 'techcross',
    workflow: {
      name: 'TECHCROSS 1-3: Equipment List',
      description: '장비 목록 생성 - AI BOM 기반 Human-in-the-Loop 검증, PUMP/TANK/ECU/FMU/HGU 검출 및 수량 집계',
      nodes: [
        { id: 'imageinput_1', type: 'imageinput', label: 'P&ID 도면 입력', parameters: {}, position: { x: 100, y: 200 } },
        { id: 'yolo_1', type: 'yolo', label: 'P&ID 심볼 검출', parameters: { model_type: 'pid_class_aware', confidence: 0.25, iou: 0.45, imgsz: 640, use_sahi: true }, position: { x: 400, y: 200 } },
        { id: 'aibom_1', type: 'blueprint-ai-bom', label: 'AI BOM 검증', parameters: {}, position: { x: 700, y: 200 } },
      ],
      edges: [
        { id: 'e1', source: 'imageinput_1', target: 'yolo_1' },
        { id: 'e2', source: 'imageinput_1', target: 'aibom_1' },
        { id: 'e3', source: 'yolo_1', target: 'aibom_1' },
      ],
    },
  },
  {
    nameKey: 'techcrossDeviation',
    descKey: 'techcrossDeviationDesc',
    useCaseKey: 'techcrossDeviationUseCase',
    estimatedTime: '20-30s',
    accuracy: '92%',
    category: 'techcross',
    workflow: {
      name: 'TECHCROSS 1-4: Deviation Analysis (AI BOM)',
      description: '편차 분석 - AI BOM 기반 Human-in-the-Loop 검증, ISO 10628/ISA 5.1/BWMS 표준 편차 검토 및 심각도 조정',
      nodes: [
        { id: 'imageinput_1', type: 'imageinput', label: 'P&ID 도면 입력', parameters: {}, position: { x: 100, y: 200 } },
        { id: 'yolo_1', type: 'yolo', label: 'P&ID 심볼 검출', parameters: { model_type: 'pid_class_aware', confidence: 0.25, iou: 0.45, imgsz: 640, use_sahi: true }, position: { x: 350, y: 100 } },
        { id: 'linedetector_1', type: 'linedetector', label: '라인 검출', parameters: { method: 'lsd', min_length: 50, classify_types: true, detect_intersections: true }, position: { x: 350, y: 300 } },
        { id: 'pidanalyzer_1', type: 'pidanalyzer', label: '연결성 분석', parameters: { generate_bom: false, generate_valve_list: false, generate_equipment_list: false }, position: { x: 600, y: 200 } },
        { id: 'pidfeatures_1', type: 'pidfeatures', label: '편차 분석', parameters: { analyze_deviation: true, standards: ['ISO_10628', 'ISA_5.1', 'BWMS'], analysis_types: ['connectivity', 'symbol_validation'] }, position: { x: 850, y: 200 } },
        { id: 'aibom_1', type: 'blueprint-ai-bom', label: '편차 검증 (AI BOM)', parameters: {}, position: { x: 1050, y: 200 } },
      ],
      edges: [
        { id: 'e1', source: 'imageinput_1', target: 'yolo_1' },
        { id: 'e2', source: 'imageinput_1', target: 'linedetector_1' },
        { id: 'e3', source: 'yolo_1', target: 'pidanalyzer_1' },
        { id: 'e4', source: 'linedetector_1', target: 'pidanalyzer_1' },
        { id: 'e5', source: 'pidanalyzer_1', target: 'pidfeatures_1' },
        { id: 'e6', source: 'imageinput_1', target: 'aibom_1' },
        { id: 'e7', source: 'pidfeatures_1', target: 'aibom_1' },
      ],
    },
  },

  // ============ DSE BEARING TEMPLATES ============
  {
    nameKey: 'dseBearingAnalysis',
    descKey: 'dseBearingAnalysisDesc',
    useCaseKey: 'dseBearingAnalysisUseCase',
    estimatedTime: '15-25s',
    accuracy: '96%',
    category: 'dsebearing',
    featured: true,
    sampleImage: '/samples/dse_bearing_assy_t1.png',
    workflow: {
      name: 'DSE Bearing 1-1: 단품 도면 분석 + AI BOM',
      description: '터빈 베어링 단품 부품도 분석 - Table Detector로 BOM 테이블 추출, 치수 OCR, 견적용 BOM 생성 (소재 사이즈 1순위)',
      nodes: [
        { id: 'imageinput_1', type: 'imageinput', label: '부품도 입력', parameters: { features: ['dimension_ocr', 'table_extraction'] }, position: { x: 100, y: 200 } },
        { id: 'tabledetector_1', type: 'table_detector', label: 'BOM 테이블 추출', parameters: { mode: 'extract', ocr_engine: 'paddle', borderless: false, confidence_threshold: 0.5, min_confidence: 50, crop_regions: ['title_block', 'revision_table', 'parts_list_right'], enable_quality_filter: true }, position: { x: 350, y: 100 } },
        { id: 'edocr2_1', type: 'edocr2', label: '치수/텍스트 OCR', parameters: { extract_dimensions: true, extract_gdt: false, language: 'ko+en', enable_crop_upscale: true, crop_preset: 'quadrants', upscale_scale: 2, upscale_denoise: 0.3 }, position: { x: 350, y: 300 } },
        { id: 'aibom_1', type: 'blueprint-ai-bom', label: '도면 검증 (AI BOM)', parameters: { drawing_type: 'dimension_bom', features: ['table_extraction', 'human_verification'] }, position: { x: 600, y: 100 } },
        { id: 'dim_updater_1', type: 'dimension_updater', label: '치수 비동기 추가', parameters: {}, position: { x: 600, y: 350 } },
      ],
      edges: [
        { id: 'e1', source: 'imageinput_1', target: 'tabledetector_1' },
        { id: 'e2', source: 'imageinput_1', target: 'edocr2_1' },
        { id: 'e3', source: 'imageinput_1', target: 'aibom_1' },
        { id: 'e4', source: 'tabledetector_1', target: 'aibom_1' },
        { id: 'e5', source: 'aibom_1', target: 'dim_updater_1' },
        { id: 'e6', source: 'edocr2_1', target: 'dim_updater_1' },
      ],
    },
  },
  {
    nameKey: 'dseBearingRingAssy',
    descKey: 'dseBearingRingAssyDesc',
    useCaseKey: 'dseBearingRingAssyUseCase',
    estimatedTime: '25-35s',
    accuracy: '94%',
    category: 'dsebearing',
    hidden: true,
    sampleImage: '/samples/dse_ring_assy_t1.png',
    workflow: {
      name: 'DSE Bearing 2-1: Bearing Ring ASSY',
      description: 'Tilting Pad(T1-T3)/Elliptical(T4-T8) 베어링 링 조립체 - Table Detector로 BOM 추출 + Babbitt 라이닝 틈새 분석',
      nodes: [
        { id: 'imageinput_1', type: 'imageinput', label: 'Ring ASSY 도면', parameters: { features: ['dimension_ocr', 'dimension_verification', 'gt_comparison'] }, position: { x: 100, y: 200 } },
        { id: 'esrgan_1', type: 'esrgan', label: '이미지 향상', parameters: { scale: 2 }, position: { x: 300, y: 200 } },
        { id: 'tabledetector_1', type: 'table_detector', label: 'BOM 테이블 추출', parameters: { mode: 'extract', ocr_engine: 'paddle', borderless: false, confidence_threshold: 0.5, min_confidence: 50, crop_regions: ['title_block', 'revision_table', 'parts_list_right'], enable_quality_filter: true }, position: { x: 500, y: 100 } },
        { id: 'edocr2_1', type: 'edocr2', label: '치수/공차 OCR', parameters: { extract_dimensions: true, extract_gdt: true, extract_tables: true }, position: { x: 500, y: 300 } },
        { id: 'aibom_1', type: 'blueprint-ai-bom', label: 'BOM 검증 (AI BOM)', parameters: { drawing_type: 'assembly', features: ['table_extraction', 'dimension_verification'] }, position: { x: 750, y: 100 } },
        { id: 'dim_updater_1', type: 'dimension_updater', label: '치수 비동기 추가', parameters: {}, position: { x: 750, y: 350 } },
        { id: 'skinmodel_1', type: 'skinmodel', label: '틈새 공차 분석', parameters: { task: 'tolerance', material_type: 'steel', correlation_length: 2.0 }, position: { x: 1000, y: 200 } },
      ],
      edges: [
        { id: 'e1', source: 'imageinput_1', target: 'esrgan_1' },
        { id: 'e2', source: 'esrgan_1', target: 'tabledetector_1' },
        { id: 'e3', source: 'esrgan_1', target: 'edocr2_1' },
        { id: 'e4', source: 'imageinput_1', target: 'aibom_1' },
        { id: 'e5', source: 'tabledetector_1', target: 'aibom_1' },
        { id: 'e6', source: 'aibom_1', target: 'dim_updater_1' },
        { id: 'e7', source: 'edocr2_1', target: 'dim_updater_1' },
        { id: 'e8', source: 'dim_updater_1', target: 'skinmodel_1' },
      ],
    },
  },
  {
    nameKey: 'dseBearingCasingAssy',
    descKey: 'dseBearingCasingAssyDesc',
    useCaseKey: 'dseBearingCasingAssyUseCase',
    estimatedTime: '25-35s',
    sampleImage: '/samples/dse_casing_assy_t1.png',
    accuracy: '93%',
    category: 'dsebearing',
    hidden: true,
    workflow: {
      name: 'DSE Bearing 2-2: Bearing Casing ASSY',
      description: '베어링 케이싱 조립체 - Table Detector + VLM으로 상하부 Split 구조, 오일 포트/나사 가공 추출',
      nodes: [
        { id: 'imageinput_1', type: 'imageinput', label: 'Casing ASSY 도면', parameters: { features: ['dimension_ocr', 'dimension_verification', 'gt_comparison'] }, position: { x: 100, y: 200 } },
        { id: 'esrgan_1', type: 'esrgan', label: '이미지 향상', parameters: { scale: 2 }, position: { x: 300, y: 200 } },
        { id: 'tabledetector_1', type: 'table_detector', label: 'BOM 테이블 추출', parameters: { mode: 'extract', ocr_engine: 'paddle', borderless: false, confidence_threshold: 0.5, min_confidence: 50, crop_regions: ['title_block', 'revision_table', 'parts_list_right'], enable_quality_filter: true }, position: { x: 500, y: 100 } },
        { id: 'edocr2_1', type: 'edocr2', label: '나사/포트 OCR', parameters: { extract_dimensions: true, extract_text: true, language: 'ko+en' }, position: { x: 500, y: 300 } },
        { id: 'aibom_1', type: 'blueprint-ai-bom', label: 'Casing 검증', parameters: { drawing_type: 'assembly', features: ['table_extraction', 'dimension_verification'] }, position: { x: 750, y: 100 } },
        { id: 'dim_updater_1', type: 'dimension_updater', label: '치수 비동기 추가', parameters: {}, position: { x: 750, y: 350 } },
        { id: 'skinmodel_1', type: 'skinmodel', label: '가공 난이도 분석', parameters: { task: 'manufacturability', material_type: 'steel', manufacturing_process: 'machining' }, position: { x: 1000, y: 200 } },
      ],
      edges: [
        { id: 'e1', source: 'imageinput_1', target: 'esrgan_1' },
        { id: 'e2', source: 'esrgan_1', target: 'tabledetector_1' },
        { id: 'e3', source: 'esrgan_1', target: 'edocr2_1' },
        { id: 'e4', source: 'imageinput_1', target: 'aibom_1' },
        { id: 'e5', source: 'tabledetector_1', target: 'aibom_1' },
        { id: 'e6', source: 'aibom_1', target: 'dim_updater_1' },
        { id: 'e7', source: 'edocr2_1', target: 'dim_updater_1' },
        { id: 'e8', source: 'dim_updater_1', target: 'skinmodel_1' },
      ],
    },
  },
  {
    nameKey: 'dseThrustBearing',
    descKey: 'dseThrustBearingDesc',
    useCaseKey: 'dseThrustBearingUseCase',
    estimatedTime: '30-40s',
    accuracy: '95%',
    category: 'dsebearing',
    hidden: true,
    sampleImage: '/samples/dse_thrust_bearing_assy.png',
    workflow: {
      name: 'DSE Bearing 2-3: Thrust Bearing',
      description: '스러스트 베어링 조립체 (TBN/GEN Side) - Table Detector + VLM으로 12개 PAD, Leveling Plate, PIVOT 분석',
      nodes: [
        { id: 'imageinput_1', type: 'imageinput', label: 'Thrust Bearing 도면', parameters: { features: ['dimension_ocr', 'dimension_verification', 'gt_comparison'] }, position: { x: 100, y: 200 } },
        { id: 'esrgan_1', type: 'esrgan', label: '이미지 향상', parameters: { scale: 2 }, position: { x: 300, y: 100 } },
        { id: 'vl_1', type: 'vl', label: 'VLM 구조 분석', parameters: { prompt: '스러스트 베어링의 PAD 배열, 상하부 케이싱 구조, 레벨링 플레이트 배치를 분석해주세요' }, position: { x: 300, y: 350 } },
        { id: 'tabledetector_1', type: 'table_detector', label: 'BOM 테이블 추출', parameters: { mode: 'extract', ocr_engine: 'paddle', borderless: false, confidence_threshold: 0.5, min_confidence: 50, crop_regions: ['title_block', 'revision_table', 'parts_list_right'], enable_quality_filter: true }, position: { x: 550, y: 50 } },
        { id: 'edocr2_1', type: 'edocr2', label: '치수/토크 OCR', parameters: { extract_dimensions: true, extract_text: true, extract_tables: true }, position: { x: 550, y: 300 } },
        { id: 'aibom_1', type: 'blueprint-ai-bom', label: 'Thrust BOM 검증', parameters: { drawing_type: 'assembly', features: ['table_extraction', 'dimension_verification', 'human_verification'] }, position: { x: 800, y: 100 } },
        { id: 'dim_updater_1', type: 'dimension_updater', label: '치수 비동기 추가', parameters: {}, position: { x: 800, y: 350 } },
        { id: 'skinmodel_1', type: 'skinmodel', label: 'PAD 틈새 분석', parameters: { task: 'tolerance', material_type: 'steel', correlation_length: 1.5 }, position: { x: 1050, y: 200 } },
        { id: 'merge_1', type: 'merge', label: '분석 통합', parameters: {}, position: { x: 1250, y: 200 } },
      ],
      edges: [
        { id: 'e1', source: 'imageinput_1', target: 'esrgan_1' },
        { id: 'e2', source: 'imageinput_1', target: 'vl_1' },
        { id: 'e3', source: 'esrgan_1', target: 'tabledetector_1' },
        { id: 'e4', source: 'esrgan_1', target: 'edocr2_1' },
        { id: 'e5', source: 'imageinput_1', target: 'aibom_1' },
        { id: 'e6', source: 'tabledetector_1', target: 'aibom_1' },
        { id: 'e7', source: 'aibom_1', target: 'dim_updater_1' },
        { id: 'e8', source: 'edocr2_1', target: 'dim_updater_1' },
        { id: 'e9', source: 'dim_updater_1', target: 'skinmodel_1' },
        { id: 'e10', source: 'vl_1', target: 'merge_1' },
        { id: 'e11', source: 'skinmodel_1', target: 'merge_1' },
      ],
    },
  },
  {
    nameKey: 'dseBearingYoloPartsListExtract',
    descKey: 'dseBearingYoloPartsListExtractDesc',
    useCaseKey: 'dseBearingYoloPartsListExtractUseCase',
    estimatedTime: '15-25s',
    accuracy: '98%',
    category: 'dsebearing',
    sampleImage: '/samples/dse_bearing_assy_t1.png',
    featured: true,
    workflow: {
      name: 'DSE Bearing 2-8: YOLO 기반 Parts List 추출',
      description: 'YOLO로 text_block 영역 검출 후 Table Detector로 테이블 구조 추출 - TATR 검출 한계 극복',
      nodes: [
        { id: 'imageinput_1', type: 'imageinput', label: '도면 입력', parameters: { features: ['dimension_ocr'] }, position: { x: 100, y: 200 } },
        { id: 'yolo_1', type: 'yolo', label: 'Parts List 영역 검출', parameters: { model_type: 'drawing', confidence: 0.35, iou: 0.45, imgsz: 1280, classes: ['text_block'] }, position: { x: 350, y: 200 } },
        { id: 'table_detector_1', type: 'table_detector', label: '테이블 구조 추출', parameters: { mode: 'extract', ocr_engine: 'paddle', borderless: false, confidence_threshold: 0.5, min_confidence: 50, crop_regions: ['title_block', 'revision_table', 'parts_list_right'], enable_quality_filter: true }, position: { x: 600, y: 200 } },
        { id: 'aibom_1', type: 'blueprint-ai-bom', label: 'Parts List 검증 (AI BOM)', parameters: { drawing_type: 'dimension_bom', features: ['table_extraction', 'human_verification'] }, position: { x: 850, y: 200 } },
      ],
      edges: [
        { id: 'e1', source: 'imageinput_1', target: 'yolo_1' },
        { id: 'e2', source: 'yolo_1', target: 'table_detector_1' },
        { id: 'e3', source: 'imageinput_1', target: 'aibom_1' },
        { id: 'e4', source: 'table_detector_1', target: 'aibom_1' },
      ],
    },
  },
  {
    nameKey: 'dseBearingFullQuote',
    descKey: 'dseBearingFullQuoteDesc',
    useCaseKey: 'dseBearingFullQuoteUseCase',
    estimatedTime: '35-45s',
    accuracy: '96%',
    category: 'dsebearing',
    sampleImage: '/samples/dse_bearing_assy_t1.png',
    featured: true,
    workflow: {
      name: 'DSE Bearing 3-2: 완전 자동 견적',
      description: 'Title Block → Parts List → Dimension → BOM Matcher → Quote Generator → Excel 견적서 자동 생성',
      nodes: [
        { id: 'imageinput_1', type: 'imageinput', label: '베어링 도면 입력', parameters: { features: ['dimension_ocr', 'dimension_verification', 'gt_comparison'] }, position: { x: 100, y: 200 } },
        { id: 'titleblock_1', type: 'titleblock', label: 'Title Block 파싱', parameters: { detection_method: 'auto', title_block_position: 'bottom_right', ocr_engine: 'paddle', company_template: 'doosan', profile: 'bearing' }, position: { x: 350, y: 100 } },
        { id: 'partslist_1', type: 'partslist', label: 'Parts List 파싱', parameters: { table_position: 'auto', ocr_engine: 'paddle', normalize_material: true, normalize_headers: true, profile: 'bearing' }, position: { x: 350, y: 300 } },
        { id: 'edocr2_1', type: 'edocr2', label: '치수 OCR', parameters: { extract_dimensions: true, extract_gdt: true }, position: { x: 600, y: 200 } },
        { id: 'dimensionparser_1', type: 'dimensionparser', label: '치수 파싱', parameters: { dimension_type: 'bearing', parse_tolerance: true, parse_gdt: true, extract_od_id: true }, position: { x: 850, y: 200 } },
        { id: 'aibom_1', type: 'blueprint-ai-bom', label: 'BOM 세션 생성 (AI BOM)', parameters: { drawing_type: 'assembly', features: ['table_extraction', 'dimension_verification', 'bom_generation'] }, position: { x: 850, y: 400 } },
        { id: 'bommatcher_1', type: 'bommatcher', label: 'BOM 통합 + 견적', parameters: { match_strategy: 'hybrid', confidence_threshold: 0.7, include_dimensions: true, validate_material: true, generate_quote: true, customer_id: 'DSE', material_markup: 1.3, labor_markup: 1.5 }, position: { x: 1100, y: 200 } },
        { id: 'quotegenerator_1', type: 'quotegenerator', label: '견적서 출력', parameters: { currency: 'KRW', tax_rate: 10, quantity_discount: true }, position: { x: 1350, y: 200 } },
      ],
      edges: [
        { id: 'e1', source: 'imageinput_1', target: 'titleblock_1' },
        { id: 'e2', source: 'imageinput_1', target: 'partslist_1' },
        { id: 'e3', source: 'imageinput_1', target: 'edocr2_1' },
        { id: 'e4', source: 'edocr2_1', target: 'dimensionparser_1' },
        { id: 'e5', source: 'titleblock_1', target: 'bommatcher_1' },
        { id: 'e6', source: 'partslist_1', target: 'bommatcher_1' },
        { id: 'e7', source: 'dimensionparser_1', target: 'bommatcher_1' },
        { id: 'e8', source: 'bommatcher_1', target: 'quotegenerator_1' },
        { id: 'e9', source: 'imageinput_1', target: 'aibom_1' },
        { id: 'e10', source: 'edocr2_1', target: 'aibom_1' },
      ],
    },
  },

  // ============ PANASIA TEMPLATES ============
  {
    nameKey: 'panasiaMcpPanelBom',
    descKey: 'panasiaMcpPanelBomDesc',
    useCaseKey: 'panasiaMcpPanelBomUseCase',
    estimatedTime: '10-15s',
    accuracy: '95%',
    category: 'panasia',
    featured: true,
    sampleImage: '/samples/sample7_mcp_panel_body.jpg',
    sampleGT: '/samples/gt/sample7_mcp_panel_body.txt',
    workflow: {
      name: 'PANASIA: MCP Panel 심볼 검출 + GT 비교',
      description: 'MCP Panel 도면에서 27종 전력 설비 심볼 검출 → GT와 비교 → Human-in-the-Loop 검증 → BOM 내보내기. 라인 연결성 분석 없이 심볼만 집중.',
      nodes: [
        { id: 'imageinput_1', type: 'imageinput', label: 'MCP Panel 도면 입력', parameters: { features: ['symbol_detection', 'symbol_verification', 'gt_comparison'] }, position: { x: 100, y: 200 } },
        { id: 'yolo_1', type: 'yolo', label: '파나시아 심볼 검출 (27종)', parameters: { model_type: 'panasia', confidence: 0.40, iou: 0.5, imgsz: 1024 }, position: { x: 400, y: 200 } },
        { id: 'aibom_1', type: 'blueprint-ai-bom', label: 'GT 비교 + 검증 (AI BOM)', parameters: { drawing_type: 'electrical_panel' }, position: { x: 700, y: 200 } },
      ],
      edges: [
        { id: 'e1', source: 'imageinput_1', target: 'yolo_1' },
        { id: 'e2', source: 'imageinput_1', target: 'aibom_1' },
        { id: 'e3', source: 'yolo_1', target: 'aibom_1' },
      ],
    },
  },

  // ============ BASIC TEMPLATES ============
  {
    nameKey: 'speedPipeline',
    descKey: 'speedPipelineDesc',
    useCaseKey: 'speedPipelineUseCase',
    estimatedTime: '8-12s',
    accuracy: '94%',
    category: 'basic',
    workflow: {
      name: 'Speed Pipeline',
      description: 'Fast pipeline with AI BOM Human-in-the-Loop verification',
      nodes: [
        { id: 'imageinput_1', type: 'imageinput', label: 'Image Input', parameters: {}, position: { x: 100, y: 100 } },
        { id: 'yolo_1', type: 'yolo', label: 'YOLO Detection', parameters: { confidence: 0.5, imgsz: 640 }, position: { x: 350, y: 100 } },
        { id: 'aibom_1', type: 'blueprint-ai-bom', label: 'Verification (AI BOM)', parameters: {}, position: { x: 600, y: 100 } },
        { id: 'edocr2_1', type: 'edocr2', label: 'Korean OCR', parameters: {}, position: { x: 850, y: 100 } },
      ],
      edges: [
        { id: 'e1', source: 'imageinput_1', target: 'yolo_1' },
        { id: 'e2', source: 'imageinput_1', target: 'aibom_1' },
        { id: 'e3', source: 'yolo_1', target: 'aibom_1' },
        { id: 'e4', source: 'aibom_1', target: 'edocr2_1' },
      ],
    },
  },
  {
    nameKey: 'basicOCR',
    descKey: 'basicOCRDesc',
    useCaseKey: 'basicOCRUseCase',
    estimatedTime: '10-15s',
    accuracy: '95%',
    category: 'basic',
    workflow: {
      name: 'Basic OCR Pipeline',
      description: 'OCR workflow with AI BOM Human-in-the-Loop and tolerance analysis',
      nodes: [
        { id: 'imageinput_1', type: 'imageinput', label: 'Image Input', parameters: {}, position: { x: 100, y: 100 } },
        { id: 'yolo_1', type: 'yolo', label: 'YOLO Detection', parameters: { confidence: 0.5 }, position: { x: 350, y: 100 } },
        { id: 'aibom_1', type: 'blueprint-ai-bom', label: 'Verification (AI BOM)', parameters: {}, position: { x: 600, y: 100 } },
        { id: 'edocr2_1', type: 'edocr2', label: 'Korean OCR', parameters: {}, position: { x: 850, y: 100 } },
        { id: 'skinmodel_1', type: 'skinmodel', label: 'Tolerance Analysis', parameters: {}, position: { x: 1100, y: 100 } },
      ],
      edges: [
        { id: 'e1', source: 'imageinput_1', target: 'yolo_1' },
        { id: 'e2', source: 'imageinput_1', target: 'aibom_1' },
        { id: 'e3', source: 'yolo_1', target: 'aibom_1' },
        { id: 'e4', source: 'aibom_1', target: 'edocr2_1' },
        { id: 'e5', source: 'edocr2_1', target: 'skinmodel_1' },
      ],
    },
  },

  // ============ ADVANCED TEMPLATES ============
  {
    nameKey: 'accuracyPipeline',
    descKey: 'accuracyPipelineDesc',
    useCaseKey: 'accuracyPipelineUseCase',
    estimatedTime: '15-20s',
    accuracy: '97%',
    category: 'advanced',
    workflow: {
      name: 'Accuracy Pipeline',
      description: 'High accuracy with AI BOM Human-in-the-Loop, dual OCR and segmentation',
      nodes: [
        { id: 'imageinput_1', type: 'imageinput', label: 'Image Input', parameters: {}, position: { x: 100, y: 100 } },
        { id: 'yolo_1', type: 'yolo', label: 'YOLO Detection', parameters: { confidence: 0.35, imgsz: 1280 }, position: { x: 300, y: 100 } },
        { id: 'aibom_1', type: 'blueprint-ai-bom', label: 'Verification (AI BOM)', parameters: {}, position: { x: 500, y: 100 } },
        { id: 'edgnet_1', type: 'edgnet', label: 'Edge Segmentation', parameters: { threshold: 0.5 }, position: { x: 700, y: 100 } },
        { id: 'edocr2_1', type: 'edocr2', label: 'Korean OCR', parameters: {}, position: { x: 900, y: 50 } },
        { id: 'paddleocr_1', type: 'paddleocr', label: 'PaddleOCR', parameters: { lang: 'en' }, position: { x: 900, y: 150 } },
        { id: 'merge_1', type: 'merge', label: 'Merge Results', parameters: {}, position: { x: 1100, y: 100 } },
      ],
      edges: [
        { id: 'e1', source: 'imageinput_1', target: 'yolo_1' },
        { id: 'e2', source: 'imageinput_1', target: 'aibom_1' },
        { id: 'e3', source: 'yolo_1', target: 'aibom_1' },
        { id: 'e4', source: 'aibom_1', target: 'edgnet_1' },
        { id: 'e5', source: 'edgnet_1', target: 'edocr2_1' },
        { id: 'e6', source: 'edgnet_1', target: 'paddleocr_1' },
        { id: 'e7', source: 'edocr2_1', target: 'merge_1' },
        { id: 'e8', source: 'paddleocr_1', target: 'merge_1' },
      ],
    },
  },
  {
    nameKey: 'ocrEnsemble',
    descKey: 'ocrEnsembleDesc',
    useCaseKey: 'ocrEnsembleUseCase',
    estimatedTime: '18-25s',
    accuracy: '98%',
    category: 'advanced',
    workflow: {
      name: 'OCR Ensemble Pipeline',
      description: 'AI BOM Human-in-the-Loop with 4-engine OCR ensemble voting and tolerance analysis',
      nodes: [
        { id: 'imageinput_1', type: 'imageinput', label: 'Image Input', parameters: {}, position: { x: 100, y: 150 } },
        { id: 'esrgan_1', type: 'esrgan', label: 'ESRGAN Upscale', parameters: { scale: 2 }, position: { x: 300, y: 150 } },
        { id: 'yolo_1', type: 'yolo', label: 'YOLO Detection', parameters: { confidence: 0.3, imgsz: 1280 }, position: { x: 500, y: 150 } },
        { id: 'aibom_1', type: 'blueprint-ai-bom', label: 'Verification (AI BOM)', parameters: {}, position: { x: 700, y: 150 } },
        { id: 'ocr_ensemble_1', type: 'ocr_ensemble', label: 'OCR Ensemble (4-way)', parameters: {}, position: { x: 950, y: 50 } },
        { id: 'edocr2_1', type: 'edocr2', label: 'Dimension OCR', parameters: {}, position: { x: 950, y: 250 } },
        { id: 'skinmodel_1', type: 'skinmodel', label: 'Tolerance Analysis', parameters: {}, position: { x: 1200, y: 250 } },
      ],
      edges: [
        { id: 'e1', source: 'imageinput_1', target: 'esrgan_1' },
        { id: 'e2', source: 'esrgan_1', target: 'yolo_1' },
        { id: 'e3', source: 'esrgan_1', target: 'aibom_1' },
        { id: 'e4', source: 'yolo_1', target: 'aibom_1' },
        { id: 'e5', source: 'aibom_1', target: 'ocr_ensemble_1' },
        { id: 'e6', source: 'aibom_1', target: 'edocr2_1' },
        { id: 'e7', source: 'edocr2_1', target: 'skinmodel_1' },
      ],
    },
  },
  {
    nameKey: 'multiOCRComparison',
    descKey: 'multiOCRComparisonDesc',
    useCaseKey: 'multiOCRComparisonUseCase',
    estimatedTime: '18-25s',
    accuracy: '96%',
    category: 'advanced',
    workflow: {
      name: 'Multi-OCR Comparison',
      description: 'AI BOM Human-in-the-Loop with 4 OCR engine comparison',
      nodes: [
        { id: 'imageinput_1', type: 'imageinput', label: 'Image Input', parameters: {}, position: { x: 100, y: 200 } },
        { id: 'yolo_1', type: 'yolo', label: 'YOLO Detection', parameters: { confidence: 0.4 }, position: { x: 300, y: 200 } },
        { id: 'aibom_1', type: 'blueprint-ai-bom', label: 'Verification (AI BOM)', parameters: {}, position: { x: 500, y: 200 } },
        { id: 'edocr2_1', type: 'edocr2', label: 'eDOCr2', parameters: {}, position: { x: 750, y: 80 } },
        { id: 'paddleocr_1', type: 'paddleocr', label: 'PaddleOCR', parameters: {}, position: { x: 750, y: 160 } },
        { id: 'tesseract_1', type: 'tesseract', label: 'Tesseract', parameters: {}, position: { x: 750, y: 240 } },
        { id: 'easyocr_1', type: 'easyocr', label: 'EasyOCR', parameters: { languages: ['en'] }, position: { x: 750, y: 320 } },
        { id: 'merge_1', type: 'merge', label: 'Compare & Merge', parameters: {}, position: { x: 1000, y: 200 } },
      ],
      edges: [
        { id: 'e1', source: 'imageinput_1', target: 'yolo_1' },
        { id: 'e2', source: 'imageinput_1', target: 'aibom_1' },
        { id: 'e3', source: 'yolo_1', target: 'aibom_1' },
        { id: 'e4', source: 'aibom_1', target: 'edocr2_1' },
        { id: 'e5', source: 'aibom_1', target: 'paddleocr_1' },
        { id: 'e6', source: 'aibom_1', target: 'tesseract_1' },
        { id: 'e7', source: 'aibom_1', target: 'easyocr_1' },
        { id: 'e8', source: 'edocr2_1', target: 'merge_1' },
        { id: 'e9', source: 'paddleocr_1', target: 'merge_1' },
        { id: 'e10', source: 'tesseract_1', target: 'merge_1' },
        { id: 'e11', source: 'easyocr_1', target: 'merge_1' },
      ],
    },
  },

  // ============ BENCHMARK TEMPLATES ============
  {
    nameKey: 'fullOCRBenchmark',
    descKey: 'fullOCRBenchmarkDesc',
    useCaseKey: 'fullOCRBenchmarkUseCase',
    estimatedTime: '15-25s',
    accuracy: 'Comparison',
    category: 'benchmark',
    workflow: {
      name: 'Full OCR Benchmark',
      description: 'Compare 5 active OCR engines side-by-side for comprehensive evaluation',
      nodes: [
        { id: 'imageinput_1', type: 'imageinput', label: 'Image Input', parameters: {}, position: { x: 50, y: 200 } },
        { id: 'edocr2_1', type: 'edocr2', label: 'eDOCr2 (Drawing)', parameters: {}, position: { x: 350, y: 50 } },
        { id: 'paddleocr_1', type: 'paddleocr', label: 'PaddleOCR (Fast)', parameters: { lang: 'en' }, position: { x: 350, y: 130 } },
        { id: 'tesseract_1', type: 'tesseract', label: 'Tesseract (General)', parameters: { lang: 'eng' }, position: { x: 350, y: 210 } },
        { id: 'easyocr_1', type: 'easyocr', label: 'EasyOCR (Multilingual)', parameters: { languages: ['en'] }, position: { x: 350, y: 290 } },
        { id: 'ocr_ensemble_1', type: 'ocr_ensemble', label: 'Ensemble (Voting)', parameters: {}, position: { x: 350, y: 370 } },
        { id: 'merge_1', type: 'merge', label: 'All OCR Results', parameters: {}, position: { x: 650, y: 200 } },
      ],
      edges: [
        { id: 'e1', source: 'imageinput_1', target: 'edocr2_1' },
        { id: 'e2', source: 'imageinput_1', target: 'paddleocr_1' },
        { id: 'e3', source: 'imageinput_1', target: 'tesseract_1' },
        { id: 'e4', source: 'imageinput_1', target: 'easyocr_1' },
        { id: 'e5', source: 'imageinput_1', target: 'ocr_ensemble_1' },
        { id: 'e6', source: 'edocr2_1', target: 'merge_1' },
        { id: 'e7', source: 'paddleocr_1', target: 'merge_1' },
        { id: 'e8', source: 'tesseract_1', target: 'merge_1' },
        { id: 'e9', source: 'easyocr_1', target: 'merge_1' },
        { id: 'e10', source: 'ocr_ensemble_1', target: 'merge_1' },
      ],
    },
  },
  {
    nameKey: 'detectionBenchmark',
    descKey: 'detectionBenchmarkDesc',
    useCaseKey: 'detectionBenchmarkUseCase',
    estimatedTime: '10-15s',
    accuracy: 'Comparison',
    category: 'benchmark',
    workflow: {
      name: 'Detection Benchmark',
      description: 'Compare YOLO models: engineering vs P&ID specialized detection',
      nodes: [
        { id: 'imageinput_1', type: 'imageinput', label: 'Image Input', parameters: {}, position: { x: 50, y: 200 } },
        { id: 'yolo_1', type: 'yolo', label: 'YOLO (Engineering)', parameters: { model_type: 'engineering', confidence: 0.35, imgsz: 1280 }, position: { x: 350, y: 100 } },
        { id: 'yolo_2', type: 'yolo', label: 'YOLO (BOM Detector)', parameters: { model_type: 'bom_detector', confidence: 0.4, imgsz: 1024 }, position: { x: 350, y: 180 } },
        { id: 'yolo_3', type: 'yolo', label: 'YOLO (P&ID)', parameters: { model_type: 'pid_class_aware', confidence: 0.25, imgsz: 640, use_sahi: true }, position: { x: 350, y: 260 } },
        { id: 'yolo_4', type: 'yolo', label: 'YOLO (P&ID Agnostic)', parameters: { model_type: 'pid_class_agnostic', confidence: 0.25, imgsz: 640, use_sahi: true }, position: { x: 350, y: 340 } },
        { id: 'merge_1', type: 'merge', label: 'Detection Comparison', parameters: {}, position: { x: 650, y: 200 } },
      ],
      edges: [
        { id: 'e1', source: 'imageinput_1', target: 'yolo_1' },
        { id: 'e2', source: 'imageinput_1', target: 'yolo_2' },
        { id: 'e3', source: 'imageinput_1', target: 'yolo_3' },
        { id: 'e4', source: 'imageinput_1', target: 'yolo_4' },
        { id: 'e5', source: 'yolo_1', target: 'merge_1' },
        { id: 'e6', source: 'yolo_2', target: 'merge_1' },
        { id: 'e7', source: 'yolo_3', target: 'merge_1' },
        { id: 'e8', source: 'yolo_4', target: 'merge_1' },
      ],
    },
  },
  {
    nameKey: 'segmentationBenchmark',
    descKey: 'segmentationBenchmarkDesc',
    useCaseKey: 'segmentationBenchmarkUseCase',
    estimatedTime: '8-12s',
    accuracy: 'Comparison',
    category: 'benchmark',
    workflow: {
      name: 'Segmentation Benchmark',
      description: 'Compare EDGNet edge segmentation vs Line Detector for different use cases',
      nodes: [
        { id: 'imageinput_1', type: 'imageinput', label: 'Image Input', parameters: {}, position: { x: 50, y: 200 } },
        { id: 'edgnet_1', type: 'edgnet', label: 'EDGNet (Default)', parameters: { threshold: 0.5 }, position: { x: 350, y: 80 } },
        { id: 'edgnet_2', type: 'edgnet', label: 'EDGNet (High Sens)', parameters: { threshold: 0.3 }, position: { x: 350, y: 160 } },
        { id: 'linedetector_1', type: 'linedetector', label: 'Line Detector (LSD)', parameters: { method: 'lsd', merge_lines: true, classify_types: true }, position: { x: 350, y: 240 } },
        { id: 'linedetector_2', type: 'linedetector', label: 'Line Detector (Hough)', parameters: { method: 'hough', merge_lines: true, classify_types: true }, position: { x: 350, y: 320 } },
        { id: 'merge_1', type: 'merge', label: 'Segmentation Comparison', parameters: {}, position: { x: 650, y: 200 } },
      ],
      edges: [
        { id: 'e1', source: 'imageinput_1', target: 'edgnet_1' },
        { id: 'e2', source: 'imageinput_1', target: 'edgnet_2' },
        { id: 'e3', source: 'imageinput_1', target: 'linedetector_1' },
        { id: 'e4', source: 'imageinput_1', target: 'linedetector_2' },
        { id: 'e5', source: 'edgnet_1', target: 'merge_1' },
        { id: 'e6', source: 'edgnet_2', target: 'merge_1' },
        { id: 'e7', source: 'linedetector_1', target: 'merge_1' },
        { id: 'e8', source: 'linedetector_2', target: 'merge_1' },
      ],
    },
  },
  {
    nameKey: 'analysisBenchmark',
    descKey: 'analysisBenchmarkDesc',
    useCaseKey: 'analysisBenchmarkUseCase',
    estimatedTime: '15-25s',
    accuracy: 'Comparison',
    category: 'benchmark',
    workflow: {
      name: 'Analysis Benchmark',
      description: 'Compare all analysis engines: SkinModel tolerance, PID Analyzer connectivity, Design Checker validation',
      nodes: [
        { id: 'imageinput_1', type: 'imageinput', label: 'Image Input', parameters: {}, position: { x: 50, y: 200 } },
        { id: 'yolo_1', type: 'yolo', label: 'YOLO Detection', parameters: { model_type: 'engineering', confidence: 0.35 }, position: { x: 250, y: 100 } },
        { id: 'yolo_2', type: 'yolo', label: 'YOLO P&ID Detection', parameters: { model_type: 'pid_class_aware', confidence: 0.25, use_sahi: true }, position: { x: 250, y: 300 } },
        { id: 'linedetector_1', type: 'linedetector', label: 'Line Detector', parameters: { method: 'lsd' }, position: { x: 250, y: 400 } },
        { id: 'edocr2_1', type: 'edocr2', label: 'Dimension OCR', parameters: {}, position: { x: 450, y: 100 } },
        { id: 'skinmodel_1', type: 'skinmodel', label: 'SkinModel (Tolerance)', parameters: {}, position: { x: 650, y: 100 } },
        { id: 'pidanalyzer_1', type: 'pidanalyzer', label: 'PID Analyzer (Connectivity)', parameters: { generate_bom: true, generate_valve_list: true }, position: { x: 650, y: 250 } },
        { id: 'designchecker_1', type: 'designchecker', label: 'Design Checker (Validation)', parameters: { severity_threshold: 'warning' }, position: { x: 650, y: 400 } },
        { id: 'merge_1', type: 'merge', label: 'Analysis Comparison', parameters: {}, position: { x: 900, y: 250 } },
      ],
      edges: [
        { id: 'e1', source: 'imageinput_1', target: 'yolo_1' },
        { id: 'e2', source: 'imageinput_1', target: 'yolo_2' },
        { id: 'e3', source: 'imageinput_1', target: 'linedetector_1' },
        { id: 'e4', source: 'yolo_1', target: 'edocr2_1' },
        { id: 'e5', source: 'edocr2_1', target: 'skinmodel_1' },
        { id: 'e6', source: 'yolo_2', target: 'pidanalyzer_1' },
        { id: 'e7', source: 'linedetector_1', target: 'pidanalyzer_1' },
        { id: 'e8', source: 'pidanalyzer_1', target: 'designchecker_1' },
        { id: 'e9', source: 'skinmodel_1', target: 'merge_1' },
        { id: 'e10', source: 'pidanalyzer_1', target: 'merge_1' },
        { id: 'e11', source: 'designchecker_1', target: 'merge_1' },
      ],
    },
  },
  {
    nameKey: 'preprocessingBenchmark',
    descKey: 'preprocessingBenchmarkDesc',
    useCaseKey: 'preprocessingBenchmarkUseCase',
    estimatedTime: '20-30s',
    accuracy: 'Comparison',
    category: 'benchmark',
    workflow: {
      name: 'Preprocessing Benchmark',
      description: 'Compare image enhancement effects: Original vs ESRGAN 2x vs ESRGAN 4x on OCR accuracy',
      nodes: [
        { id: 'imageinput_1', type: 'imageinput', label: 'Image Input', parameters: {}, position: { x: 50, y: 200 } },
        { id: 'edocr2_1', type: 'edocr2', label: 'OCR (Original)', parameters: {}, position: { x: 350, y: 50 } },
        { id: 'esrgan_1', type: 'esrgan', label: 'ESRGAN 2x', parameters: { scale: 2 }, position: { x: 250, y: 200 } },
        { id: 'edocr2_2', type: 'edocr2', label: 'OCR (2x Upscale)', parameters: {}, position: { x: 450, y: 200 } },
        { id: 'esrgan_2', type: 'esrgan', label: 'ESRGAN 4x', parameters: { scale: 4 }, position: { x: 250, y: 350 } },
        { id: 'edocr2_3', type: 'edocr2', label: 'OCR (4x Upscale)', parameters: {}, position: { x: 450, y: 350 } },
        { id: 'merge_1', type: 'merge', label: 'Quality Comparison', parameters: {}, position: { x: 650, y: 200 } },
      ],
      edges: [
        { id: 'e1', source: 'imageinput_1', target: 'edocr2_1' },
        { id: 'e2', source: 'imageinput_1', target: 'esrgan_1' },
        { id: 'e3', source: 'imageinput_1', target: 'esrgan_2' },
        { id: 'e4', source: 'esrgan_1', target: 'edocr2_2' },
        { id: 'e5', source: 'esrgan_2', target: 'edocr2_3' },
        { id: 'e6', source: 'edocr2_1', target: 'merge_1' },
        { id: 'e7', source: 'edocr2_2', target: 'merge_1' },
        { id: 'e8', source: 'edocr2_3', target: 'merge_1' },
      ],
    },
  },
  {
    nameKey: 'aiBenchmark',
    descKey: 'aiBenchmarkDesc',
    useCaseKey: 'aiBenchmarkUseCase',
    estimatedTime: '15-25s',
    accuracy: 'Comparison',
    category: 'benchmark',
    workflow: {
      name: 'AI Benchmark',
      description: 'Compare Vision-Language model responses with different prompts and contexts',
      nodes: [
        { id: 'imageinput_1', type: 'imageinput', label: 'Image Input', parameters: {}, position: { x: 50, y: 200 } },
        { id: 'textinput_1', type: 'textinput', label: 'Describe Drawing', parameters: { text: 'Describe this engineering drawing in detail' }, position: { x: 250, y: 50 } },
        { id: 'textinput_2', type: 'textinput', label: 'Extract Dimensions', parameters: { text: 'Extract all dimensions and tolerances from this drawing' }, position: { x: 250, y: 200 } },
        { id: 'textinput_3', type: 'textinput', label: 'Analyze Issues', parameters: { text: 'Identify potential issues or errors in this drawing' }, position: { x: 250, y: 350 } },
        { id: 'vl_1', type: 'vl', label: 'VL (Description)', parameters: {}, position: { x: 500, y: 50 } },
        { id: 'vl_2', type: 'vl', label: 'VL (Dimensions)', parameters: {}, position: { x: 500, y: 200 } },
        { id: 'vl_3', type: 'vl', label: 'VL (Review)', parameters: {}, position: { x: 500, y: 350 } },
        { id: 'merge_1', type: 'merge', label: 'AI Response Comparison', parameters: {}, position: { x: 750, y: 200 } },
      ],
      edges: [
        { id: 'e1', source: 'imageinput_1', target: 'vl_1' },
        { id: 'e2', source: 'imageinput_1', target: 'vl_2' },
        { id: 'e3', source: 'imageinput_1', target: 'vl_3' },
        { id: 'e4', source: 'textinput_1', target: 'vl_1' },
        { id: 'e5', source: 'textinput_2', target: 'vl_2' },
        { id: 'e6', source: 'textinput_3', target: 'vl_3' },
        { id: 'e7', source: 'vl_1', target: 'merge_1' },
        { id: 'e8', source: 'vl_2', target: 'merge_1' },
        { id: 'e9', source: 'vl_3', target: 'merge_1' },
      ],
    },
  },

  // ============ AI TEMPLATES ============
  {
    nameKey: 'vlAssisted',
    descKey: 'vlAssistedDesc',
    useCaseKey: 'vlAssistedUseCase',
    estimatedTime: '12-18s',
    accuracy: '96%',
    category: 'ai',
    workflow: {
      name: 'VL-Assisted Analysis',
      description: 'AI BOM Human-in-the-Loop with Vision-Language AI for intelligent drawing understanding',
      nodes: [
        { id: 'imageinput_1', type: 'imageinput', label: 'Drawing Input', parameters: {}, position: { x: 100, y: 150 } },
        { id: 'textinput_1', type: 'textinput', label: 'Analysis Prompt', parameters: { text: 'Analyze this engineering drawing and extract all dimensions' }, position: { x: 100, y: 300 } },
        { id: 'vl_1', type: 'vl', label: 'VL Model Analysis', parameters: {}, position: { x: 400, y: 200 } },
        { id: 'yolo_1', type: 'yolo', label: 'YOLO Detection', parameters: { confidence: 0.4 }, position: { x: 650, y: 200 } },
        { id: 'aibom_1', type: 'blueprint-ai-bom', label: 'Verification (AI BOM)', parameters: {}, position: { x: 900, y: 200 } },
      ],
      edges: [
        { id: 'e1', source: 'imageinput_1', target: 'vl_1' },
        { id: 'e2', source: 'textinput_1', target: 'vl_1' },
        { id: 'e3', source: 'vl_1', target: 'yolo_1' },
        { id: 'e4', source: 'imageinput_1', target: 'aibom_1' },
        { id: 'e5', source: 'yolo_1', target: 'aibom_1' },
      ],
    },
  },
  {
    nameKey: 'knowledgeEnhanced',
    descKey: 'knowledgeEnhancedDesc',
    useCaseKey: 'knowledgeEnhancedUseCase',
    estimatedTime: '15-20s',
    accuracy: '95%',
    category: 'ai',
    workflow: {
      name: 'AI-Enhanced Analysis',
      description: 'AI BOM Human-in-the-Loop with Vision-Language AI for context-aware analysis',
      nodes: [
        { id: 'imageinput_1', type: 'imageinput', label: 'Drawing Input', parameters: {}, position: { x: 100, y: 150 } },
        { id: 'textinput_1', type: 'textinput', label: 'Query', parameters: { text: 'Explain the GD&T symbols and tolerances in this drawing' }, position: { x: 100, y: 300 } },
        { id: 'yolo_1', type: 'yolo', label: 'Symbol Detection', parameters: { confidence: 0.4 }, position: { x: 350, y: 150 } },
        { id: 'aibom_1', type: 'blueprint-ai-bom', label: 'Verification (AI BOM)', parameters: {}, position: { x: 550, y: 150 } },
        { id: 'vl_1', type: 'vl', label: 'VL Context Analysis', parameters: {}, position: { x: 350, y: 300 } },
        { id: 'edocr2_1', type: 'edocr2', label: 'OCR', parameters: {}, position: { x: 750, y: 150 } },
        { id: 'merge_1', type: 'merge', label: 'Contextualized Results', parameters: {}, position: { x: 1000, y: 200 } },
      ],
      edges: [
        { id: 'e1', source: 'imageinput_1', target: 'yolo_1' },
        { id: 'e2', source: 'imageinput_1', target: 'aibom_1' },
        { id: 'e3', source: 'yolo_1', target: 'aibom_1' },
        { id: 'e4', source: 'imageinput_1', target: 'vl_1' },
        { id: 'e5', source: 'textinput_1', target: 'vl_1' },
        { id: 'e6', source: 'aibom_1', target: 'edocr2_1' },
        { id: 'e7', source: 'edocr2_1', target: 'merge_1' },
        { id: 'e8', source: 'vl_1', target: 'merge_1' },
      ],
    },
  },

  // ============ CONTROL FLOW TEMPLATES ============
  {
    nameKey: 'conditionalOCR',
    descKey: 'conditionalOCRDesc',
    useCaseKey: 'conditionalOCRUseCase',
    estimatedTime: '12-18s',
    accuracy: '96%',
    category: 'advanced',
    workflow: {
      name: 'Conditional OCR Pipeline',
      description: 'AI BOM Human-in-the-Loop with intelligent branching based on detection confidence',
      nodes: [
        { id: 'imageinput_1', type: 'imageinput', label: 'Image Input', parameters: {}, position: { x: 100, y: 150 } },
        { id: 'yolo_1', type: 'yolo', label: 'YOLO Detection', parameters: { confidence: 0.5 }, position: { x: 300, y: 150 } },
        { id: 'aibom_1', type: 'blueprint-ai-bom', label: 'Verification (AI BOM)', parameters: {}, position: { x: 500, y: 150 } },
        { id: 'if_1', type: 'if', label: 'Check Confidence', parameters: { condition: 'confidence > 0.8' }, position: { x: 700, y: 150 } },
        { id: 'edocr2_1', type: 'edocr2', label: 'eDOCr2 (High Conf)', parameters: {}, position: { x: 900, y: 80 } },
        { id: 'ocr_ensemble_1', type: 'ocr_ensemble', label: 'OCR Ensemble (Low Conf)', parameters: {}, position: { x: 900, y: 220 } },
        { id: 'merge_1', type: 'merge', label: 'Merge Results', parameters: {}, position: { x: 1150, y: 150 } },
      ],
      edges: [
        { id: 'e1', source: 'imageinput_1', target: 'yolo_1' },
        { id: 'e2', source: 'imageinput_1', target: 'aibom_1' },
        { id: 'e3', source: 'yolo_1', target: 'aibom_1' },
        { id: 'e4', source: 'aibom_1', target: 'if_1' },
        { id: 'e5', source: 'if_1', target: 'edocr2_1', sourceHandle: 'true' },
        { id: 'e6', source: 'if_1', target: 'ocr_ensemble_1', sourceHandle: 'false' },
        { id: 'e7', source: 'edocr2_1', target: 'merge_1' },
        { id: 'e8', source: 'ocr_ensemble_1', target: 'merge_1' },
      ],
    },
  },
  {
    nameKey: 'loopDetection',
    descKey: 'loopDetectionDesc',
    useCaseKey: 'loopDetectionUseCase',
    estimatedTime: '20-30s',
    accuracy: '98%',
    category: 'advanced',
    workflow: {
      name: 'Loop Detection Pipeline',
      description: 'AI BOM Human-in-the-Loop with iterative processing for maximum accuracy',
      nodes: [
        { id: 'imageinput_1', type: 'imageinput', label: 'Image Input', parameters: {}, position: { x: 100, y: 150 } },
        { id: 'yolo_1', type: 'yolo', label: 'YOLO Detection', parameters: { confidence: 0.35 }, position: { x: 300, y: 150 } },
        { id: 'aibom_1', type: 'blueprint-ai-bom', label: 'Verification (AI BOM)', parameters: {}, position: { x: 500, y: 150 } },
        { id: 'loop_1', type: 'loop', label: 'For Each Detection', parameters: { iterator: 'detections' }, position: { x: 700, y: 150 } },
        { id: 'edocr2_1', type: 'edocr2', label: 'OCR Each Box', parameters: {}, position: { x: 900, y: 150 } },
        { id: 'skinmodel_1', type: 'skinmodel', label: 'Tolerance Analysis', parameters: {}, position: { x: 1100, y: 150 } },
      ],
      edges: [
        { id: 'e1', source: 'imageinput_1', target: 'yolo_1' },
        { id: 'e2', source: 'imageinput_1', target: 'aibom_1' },
        { id: 'e3', source: 'yolo_1', target: 'aibom_1' },
        { id: 'e4', source: 'aibom_1', target: 'loop_1' },
        { id: 'e5', source: 'loop_1', target: 'edocr2_1' },
        { id: 'e6', source: 'edocr2_1', target: 'skinmodel_1' },
      ],
    },
  },
];
